### ISSUE TITLE
Not working with Magento 2.3.1

### ISSUE THREAD

**Issue by hetramjanghu** [yireo/Yireo_Webp2#10]
I have installed manually by downloading from Github and uploding to my server. 
After successfully instaling it throws a error **Fatal error: Uncaught Error: Class 'WebPConvert\WebPConvert' not found in /var/www/html/example.com/public_html/app/code/Yireo/Webp2/Image/Convertor.php:58 Stack trace: #0 /var/www/html/example.com/public_html/app/code/Yireo/Webp2/Plugin/ReplaceTags.php(94): Yireo\Webp2\Image\Convertor->convert('https://example...', 'https://example...') #1 /var/www/html/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Yireo\Webp2\Plugin\ReplaceTags->afterGetOutput(Object(Magento\Framework\View\Layout\Interceptor), '<div id="email"...') #2 /var/www/html/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() #3 /var/www/html/example.com/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(39): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array) #4 /var/www/html/example.com/public_html/vendor/magento/framework/View/Re in /var/www/html/example.com/public_html/app/code/Yireo/Webp2/Image/Convertor.php on line 58**

PHP version | **7.2.19-0ubuntu0.19.04.1**

Module version | **0.4.2**

GD support | **WebP is supported by GD**

**Comment by jissereitsma** [comment]
Please use our extension instructions to install this extension via composer. If you are not using composer, you will need to track all dependencies manually which you didn't. Only an installation via composer is documented here, so I would highly recommend you follow those instructions instead of trying out something that leads you into further trouble.

**Comment by hetramjanghu** [comment]
got it. thanks
