### ISSUE TITLE
Support existing <picture> structure

### ISSUE THREAD

**Issue by mattkrupnik** [yireo/Yireo_Webp2#100]
Module works like charm for simple `<img>` elements but is any possibility to support existing `<picture>` element in code? I have in code existing `<picture>` structure and it doesn't supported.

```
<picture>
    <source media="(min-width: 480px)" srcset="https://example.com/media/image-for-desktop.jpg">
    <source media="(max-width: 480px)" srcset="https://example.com/media/image-for-mobile.jpg">
    <img src="https://example.com/media/image-for-desktop.jpg">
</picture>
```

Regards
Matt

**Comment by jissereitsma** [comment]
I'm going to close this issue, as I believe this has been fixed already quite some time ago. If not, feel free to reopen.

**Comment by mobweb** [comment]
As I'm trying to optimize my product detail page for responsive images, I've added this HTML to the page:

```
<picture>
    <source media="(max-width: 768px)" srcset="https://domain.local/media/catalog/product/cache/84e037cc2361435a1deed54304eba2ca/e/l/el_.jpg">
    <source media="(min-width: 768px)" srcset="https://domain.local/media/catalog/product/cache/843d31ba4c9c6cb64dfb90af54d86664/e/l/el_.jpg">
    <img src="https://domain.local/media/catalog/product/cache/843d31ba4c9c6cb64dfb90af54d86664/e/l/el_.jpg" width="730" height="730" alt="EL" loading="eager">
</picture>
```

This is then rendered on the frontend as-is, meaning the extension does not replace the URLs with their WEBP equivalent, as it does without the <picture> logic (which I have tested).

So it seems that either this issue has not yet been fixed, or I'm doing something wrong?

**Comment by jissereitsma** [comment]
@mobweb This issue was closed earlier. If you want to address your own issue, I suggest opening up a new ticket. 

Indeed, no volunteer has popped up to create new functionality to allow for existing `picture` tags to be parsed in such a way that new next-gen images are added.
