### ISSUE TITLE
Amp pages not support <picture>

### ISSUE THREAD

**Issue by btekbtek** [yireo/Yireo_Webp2#101]
It could be helpful to disable webp if page is amp.

Amp only support <amp-img>

**Comment by btekbtek** [comment]
yes sorry, also it's a dublicate of https://github.com/yireo/Yireo_Webp2/issues/100 

basiclly its about exsistance of <picture> that it's used in amp. 

I will more dig in both modules.

**Comment by btekbtek** [comment]
Pleas close ticket.

Solution was resolved by changes in : 
Theme_dir/Yireo_NextGenImages/templates/picture.phtml

Third party module have helper that I used in your template with : 
isAmpRequest()): function.

So when is amp page I load only orginal image.


`<?php if ($this->helper(\ThirdPartyVendor\AmpModule\Helper\Data::class)->isAmpRequest()): ?>
    <?= /* @noEscape */
    $originalTag ?>

<?php else: ?>
<picture....

**Comment by jissereitsma** [comment]
Thanks for the feedback. This will definitely be useful to others if they bump into the same issue. I don't think this is material for a new feature of the Yireo WebP2 module though - that would clutter the code with all kind of hacks to get things working with other modules. Theoretically, a "compatibility module" could be created that overrides the PHTML template conditionally. But I think a template override is easier.
