### ISSUE TITLE
lazyloading compability

### ISSUE THREAD

**Issue by Naberdz** [yireo/Yireo_Webp2#106]
Hallo

if we use lazyloading from plugin https://luis-almeida.github.io/unveil/

<img class="lazyload " src="{{media url="lazyloading/blank.png"}}" data-src="{{media url="wysiwyg/banner/image.png"}}" alt="">

we get following result:
`<picture class="lazyload ">
            <source type="image/webp" data-srcset="/media/wysiwyg/banner/image.webp">
        <source type="image/jpg" data-srcset="/media/wysiwyg/banner/image.png">
    <img class="" src="/media/wysiwyg/banner/image.png" data-src="/media/wysiwyg/banner/image.png" alt="" loading="lazy"></picture>`

**Comment by jissereitsma** [comment]
From one developer to another, this leaves me with various questions:

1) This WebP extension makes use of `picture` tags. Can you confirm that the jQuery plugin you are mentioning is supporting `picture` tags? It is not in the documentation.

2) Are you aware that browsers nowadays support lazy loading without any JavaScript?

3) Are you aware that this WebP extension supports this native lazy loading? But using 2 lazy loading techniques simultanously makes no sense. Why did you keep the lazy loading setting in this plugin enabled?

**Comment by Naberdz** [comment]
@jissereitsma  It's used by theme. i can disable it but we have to rewrite templates to exclude this lazyloading.

another question if we use gif(animation) image it is also affected by the module which gives us blank gif image. is it possible to exclude gifs from it ?

**Comment by jissereitsma** [comment]
True, but as you mentioned you can also disable lazy loading in the WebP extension. But if you are looking into integrating WebP (which requires a `picture` tag) and this custom theming effect, it makes sense to first check whether that jQuery plugin you mentioned supports `picture` tags in the first place.

As for the GIF support, I'm not sure if I follow you. Are you saying that the WebP extension supports GIF? Or are you asking a question on your own lazy loading plugin that supports GIF?

**Comment by Naberdz** [comment]
@jissereitsma Wel it was also converted to picture tag but instead of gif animation we had blank image.

**Comment by jissereitsma** [comment]
I don't understand. Not every `picture` tag in the code will be converted by this WebP extension. Could you copy-and-paste the relevant `picture` tag so I better understand this? Please note that the WebP extension does not pick up anywhere on GIFs, so this surprises me. Are you sure that you have tested this properly? In other words, while the WebP extension is disabled, the problem does not occur, and when the extension is enabled, the problem occurs?
