### ISSUE TITLE
Largest Contentful Paint image was lazily loaded 

### ISSUE THREAD

**Issue by emirajbbd** [yireo/Yireo_Webp2#111]
Above-the-fold images that are lazily loaded render later in the page lifecycle, which can delay the largest contentful paint.
https://web.dev/lcp-lazy-loading/?utm_source=lighthouse&utm_medium=lr

Is there any way to exclude specific image from lazy loading. If no, then do you have a plan to add a specific class which will exclude images from being lazy loading.

**Comment by jissereitsma** [comment]
No, this feature is not supported. Also, a module that is responsible for converting existing images to WebP images, should not focus to much upon other tasks. What you mention about lazy loading is very specialistic and can only be done if there is logic behind above-the-fold and below-the-fold. I would say you can create a custom module for this and then disable lazy loading in this extension.

**Comment by jesperingels** [comment]
Hi @emirajbbd,

This is now made possible in the latest version of the Yiro_NextGenImages module -> [Pull request](https://github.com/yireo/Yireo_NextGenImages/issues/52)

So when you add `fetchpriority="high"` to an image it will remove the `loading="lazy"` attribute which greatly improves the LCP score!
