### ISSUE TITLE
Magento 2.3.5-p2 error

### ISSUE THREAD

**Issue by wdhrudra** [yireo/Yireo_Webp2#114]
main.CRITICAL: Class Yireo\NextGenImages\Block\Adminhtml\System\Config\ModuleVersion does not exist [] []
 main.CRITICAL: Invalid block type: Yireo\Webp2\VirtualType\Block\Adminhtml\System\Config\ModuleVersion [] []

**Comment by jissereitsma** [comment]
Which version of WebP2 are you using?

**Comment by wdhrudra** [comment]
Thanks for your reply.

I installed "Yireo_NextGenImages" from https://github.com/yireo/Yireo_NextGenImages

Now, its showing,

===========================
{"0":"URL \"pub\/media\/banner1.png\" is not matched with a local file","1":"#1 Yireo\\NextGenImages\\Image\\ImageFactory->createFromUrl('pub\/media\/banner...') called at [app\/code\/Yireo\/NextGenImages\/Image\/ImageCollector.php:47]\n#2 Yireo\\NextGenImages\\Image\\ImageCollector->collect('pub\/media\/banner...') called at [app\/code\/Yireo\/NextGenImages\/Util\/HtmlReplacer.php:75]\n#3 Yireo\\NextGenImages\\Util\\HtmlReplacer->replace('\\n\\n<script type=\"...') called at [app\/code\/Yireo\/NextGenImages\/Plugin\/ReplaceTagsPlugin.php:52]\n#4 Yireo\\NextGenImages\\Plugin\\ReplaceTagsPlugin->afterGetOutput(&Magento\\Framework\\View\\Layout\\Interceptor#0000000005f0d248000000006698d3c7#, '\\n\\n<script type=\"...') called at [vendor\/magento\/framework\/Interception\/Interceptor.php:146]\n#5 Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#6 Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', array(), array(array('Yireo_NextGenIma...', 'layout-model-cac...'))) called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:494]\n#7 Magento\\Framework\\View\\Layout\\Interceptor->getOutput() called at [vendor\/magento\/framework\/View\/Result\/Page.php:258]\n#8 Magento\\Framework\\View\\Result\\Page->render(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000005f0d0e0000000006698d3c7#) called at [vendor\/magento\/framework\/View\/Result\/Layout.php:171]\n#9 Magento\\Framework\\View\\Result\\Layout->renderResult(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000005f0d0e0000000006698d3c7#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#10 Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', array(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000005f0d0e0000000006698d3c7#)) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#11 Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000005f0d0e0000000006698d3c7#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#12 Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', array(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000005f0d0e0000000006698d3c7#), array(array('result-messages', 'result-builtin-c...', 'result-varnish-c...'))) called at [generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php:130]\n#13 Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000005f0d0e0000000006698d3c7#) called at [vendor\/magento\/framework\/App\/Http.php:120]\n#14 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#15 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#16 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#0000000005f0d0f9000000006698d3c7#) called at [index.php:65]\n","url":"\/","script_name":"\/index.php","report_id":"99f4a37ee4fd3d4df5111a15c689a5085ffe7f305116c60547b6c36b0e735301"}

========================================================


My backend settings are:
![image](https://user-images.githubusercontent.com/25917468/158926079-c1699343-9a9c-4139-922d-001ce6295335.png)


and 

![image](https://user-images.githubusercontent.com/25917468/158926158-5f81f5e1-6b6c-48b6-bc3e-27322b012cd8.png)


Your help will be appreciated

**Comment by jissereitsma** [comment]
Why are you not using `composer` as instructed? https://github.com/yireo/Yireo_Webp2/blob/master/INSTALL.md
