### ISSUE TITLE
How to convert for all the product images?

### ISSUE THREAD

**Issue by MagePsycho** [yireo/Yireo_Webp2#115]
When I disable the cache and visit the pages, the `jpg`, `png` to `webp` conversion works fine.

But how to convert for all the products at once via CLI? Am I missing the documentation?

**Comment by jissereitsma** [comment]
There is a CLI of the NextGenImages, with commands like `next-gen-images:convert`. But this is more for testing and not so good for performance. If you would try to convert all images for a catalog of 10k products, then this could easily lead to 40k images. Either this would give PHP timeouts, or it would lead to the Magento bootstrap being kickstarted numerous times. Either way, PHP is not the best processing tool for this.

I would recommend to use a simple `find` plus `convert` (part of the Linux distro of Imagick) instead: `find . -type f -name \*.jpg | while read IMAGE do; convert $IMAGE ${IMAGE/.jpg/.webp}; done`. Or something.

**Comment by MagePsycho** [comment]
> There is a CLI of the NextGenImages, with commands like `next-gen-images:convert`. But this is more for testing and not so good for performance. If you would try to convert all images for a catalog of 10k products, then this could easily lead to 40k images. Either this would give PHP timeouts, or it would lead to the Magento bootstrap being kickstarted numerous times. Either way, PHP is not the best processing tool for this.
> 
> I would recommend to use a simple `find` plus `convert` (part of the Linux distro of Imagick) instead: `find . -type f -name \*.jpg | while read IMAGE do; convert $IMAGE ${IMAGE/.jpg/.webp}; done`. Or something.

Thanks. Well noted.

What about using some `cache-warmer` tool that loops over all the links from `sitemap.xml`?

**Comment by jissereitsma** [comment]
Such a cache warmer would simply visit the pages and if those pages would contain the WebP picture tag, while there would be source images (like WebP) in that picture tag that are not existing yet, then those source images would simply be created.

**Comment by reshadzazai** [comment]
@jissereitsma "Then those source images would simply be created." Can you please point out which function checks and create the webp if it does not exist?

**Comment by jissereitsma** [comment]
@reshadzazai There is not a single function for this. Some pointers: Check the wrapper (https://github.com/yireo/Yireo_Webp2/blob/master/Convertor/ConvertWrapper.php), the CLI tools of this Yireo WebP2 module, and functions like https://github.com/yireo/Yireo_NextGenImages/blob/master/Util/File.php#L106 . To see the coherence, the source needs to be studied.

The fact that you are asking for a single point, suggests that you have a problem (that you didn't mention yet) and are looking for a certain solution (that you didn't describe yet). Because of this, the best definition would be that "those sources images would simply be created" ... by the Yireo WebP2 module. Every line of code is created for that purpose :)

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity. Feel free to reopen if needed.

**Comment by rostilos** [comment]
Had the same question, wrote a small .sh script to do it. Maybe it will be useful for someone
`#!/bin/bash
start=`date +%s`
directory="../pub/media"

cd "$directory" || exit
find . -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png \) -print0 |

while IFS= read -r -d $'\0' file;
  do
    filename=$(basename -- "$file")
    new_filename="${filename%.*}.webp"
    new_filepath="$(dirname "$file")/$new_filename"
    echo "Converting: $file -> $new_filepath"
    cwebp -q 80 -quiet "$file" -o "$new_filepath"
  done

end=`date +%s`
runtime=$((end-start))

echo "Execution completed in $runtime seconds."
`

**Comment by jissereitsma** [comment]
Thanks @rostilos - I added my own suggestion and your suggestion to the `README`: https://github.com/yireo/Yireo_Webp2/blob/master/README.md

**Comment by rostilos** [comment]
@jissereitsma 
Thank you!
Also wanted to ask to take a look at this repository. 
There is 1 more script there, just to remove all .webp ( generated by the module ), which can be useful for testing different configurations
https://github.com/rostilos/yireo-webp-2-shell-scripts
