### ISSUE TITLE
Invalid block type exeption

### ISSUE THREAD

**Issue by killday** [yireo/Yireo_Webp2#12]
Hi,
After installation and enabling the module I'm getting this:
![image](https://user-images.githubusercontent.com/6714294/66700707-85563580-eceb-11e9-89d3-e616a836bf22.png)

Magento 2.2.0, PHP 7.1.3, Module version 0.4.3

**Comment by jissereitsma** [comment]
Unfortunately, I can't reproduce this in the latest 2.2.X branch. The error mentions that the block `webp-script` is not created while it is correctly mentioned in the XML layout https://github.com/yireo/Yireo_Webp2/blob/master/view/frontend/layout/default.xml I assume you have refreshed the cache properly and you have installed this module via `composer`. There is something specific in your environment that is causing this error to occur.

Is there any reason why you are using a less secure Magento 2.2.0 release with known security issues?

**Comment by killday** [comment]
Thanks for the fast replay. Unfortunately a there was a person before me that develop the site and made some core changes :( . I'm still trying to locate them so I can update Magento. I'll try reinstall the module and see what happens.

**Comment by georgios-2317** [comment]
Changing to this worked for me:

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceContainer name="after.body.start">
            <block class="Magento\Framework\View\Element\Template" name="webp-script" template="Yireo_Webp2::script.phtml">
                <arguments>
                    <argument name="browser_support" xsi:type="object">Yireo\Webp2\Browser\BrowserSupport</argument>
                </arguments>
            </block>
        </referenceContainer>
    </body>
</page>
```

**Comment by jissereitsma** [comment]
@georgios-2317 As far as I can see, the only change is in this line: https://github.com/yireo/Yireo_Webp2/blob/master/view/frontend/layout/default.xml#L5 This assumes that you are using Magento 2.2.0 and not Magento 2.2.1 or anything newer. Is that correct?

**Comment by georgios-2317** [comment]
> @georgios-2317 As far as I can see, the only change is in this line: https://github.com/yireo/Yireo_Webp2/blob/master/view/frontend/layout/default.xml#L5 This assumes that you are using Magento 2.2.0 and not Magento 2.2.1 or anything newer. Is that correct?

That is correct @jissereitsma !

**Comment by jissereitsma** [comment]
A new release is properly checking now for Magento 2.2.1 or later. But unfortunately that doesn't do the failed check for previous releases. Out of interest: Why are you not upgrading from 2.2.0 to 2.2.1 knowing about its fixes and security updates? I would understand that you are withholding an upgrade to 2.3 with all of its new features, but 2.2.1 is a minor update with few upgrade issues.

**Comment by georgios-2317** [comment]
Yeah planning to but with a production system 99.9% up an multiple in-depth customizations, not much time left to do any upgrade (and heavy testing required).

**Comment by jissereitsma** [comment]
Cool. I'll close this issue for now.
