### ISSUE TITLE
Issue with https vs http

### ISSUE THREAD

**Issue by sunilit42** [yireo/Yireo_Webp2#122]
https://github.com/yireo/Yireo_NextGenImages/blob/master/Util/UrlConvertor.php#L110

creating issue with https vs http

as that line convert into http and getMediaUrl and static url getting with https so no condition matching so no image convert into webp image

https://github.com/yireo/Yireo_NextGenImages/commit/665e4f442e7c3893b02353580d44056cfce70479 i think this code change creating issue

**Comment by jissereitsma** [comment]
Thanks for spotting this. I've released a new version 0.3.7 right away. Note that this issue could / should have created on the other repo instead, because it was a bug with that extension, not this one.

Feel free to re-open this issue, if it is not fixed yet.

**Comment by jissereitsma** [comment]
@haihv433 So did you upgrade (as the fix that I mentioned to be releasing, was released when posting earlier)?

**Comment by sunilit42** [comment]
@jissereitsma  still same one issue
https://github.com/yireo/Yireo_NextGenImages/blob/master/Util/UrlConvertor.php#L140
https vs http issue

**Comment by jissereitsma** [comment]
Thanks. The same fix is now applied to the function `getBaseUrl` as well, so that should overcome this issue. Version is 0.3.9.

**Comment by jissereitsma** [comment]
@sunilit42 There are also many people that are using this plugin without issues. I have to admit that other issues are open too long. But referring to them to put pressure doesn't help. If you can collaborate on fixing all issues, then please do. Otherwise, except that I'm just doing this on voluntary basis, spending hours and hours, without asking money.

I assume the current issue is fixed and this ticket can be closed again.

**Comment by jissereitsma** [comment]
@sunilit42 I think this issue closed, so let's discuss progress on other issues with those other issues. Version 0.3.10 includes fixes for https://github.com/yireo/Yireo_NextGenImages/issues/16 but I found the discussion a bit like "hey, dropping regex and going for DOMDocument" to be less productive. Let's discuss specific improvements in the issues that are relevant and in the way that it moves things forward.

**Comment by sunilit42** [comment]
@jissereitsma ya i see and works fine
one more issue found while testing
- minicart image not showing webp image
- background css image ( i know that is not possible)

**Comment by jissereitsma** [comment]
This issue is really really closed. Could you report this by creating new issues? Otherwise this open source project becomes impossible to manage.
