### ISSUE TITLE
504 page when no review with product page

### ISSUE THREAD

**Issue by sunilit42** [yireo/Yireo_Webp2#129]
https://github.com/yireo/Yireo_NextGenImages/blob/master/Observer/ReplaceBlockHtml.php#L73

I think we need to add to condition if html contain sting then do that stuff, otherwise getting error

**Comment by jissereitsma** [comment]
Could you please comment on what causes you to suggest this change? Is there an error or a warning? For which specific page would the transport of an HTML event when outputting a Magento page be blank?

**Comment by sunilit42** [comment]
[2022-08-01 05:34:47] report.CRITICAL: Warning: DOMDocument::loadHTML(): Empty string supplied as input in /srv/public_html/vendor/yireo/magento2-next-gen-images/Util/HtmlReplacer.php on line 139 


- This is happen for ajax review loading on product page 
- open any product page, that does not contain any review 
- you will see this error loadHTML(): Empty string supplied as input into log file

**Comment by jissereitsma** [comment]
Could you confirm the version you are using?

**Comment by sunilit42** [comment]
"name": "yireo/magento2-webp2",
 "version": "0.12.1",

**Comment by jissereitsma** [comment]
Thanks. Could you upgrade to the latest versions of NextGenImages and WebP2 to see if this fixes your issue? It would be a bit silly to troubleshoot issues that are already fixed.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity. Feel free to reopen if needed.
