### ISSUE TITLE
Error with magepack bundle

### ISSUE THREAD

**Issue by walkwizus** [yireo/Yireo_Webp2#130]
Hi,

When I'm using magepack to bundle all JS, there are an error due to this file: https://github.com/yireo/Yireo_Webp2/blob/master/view/frontend/web/js/add-webp-class-to-body.js

The semicolon is missing and it break on the frontend. Can you add it ? Can you add an end of file too ? Impossible to patch it without this character.

Thanks !

**Comment by jissereitsma** [comment]
Thanks for reporting this. I've released a new version with this fix right away.

By the way, do you know you can edit a file on GitHub and create a Pull Request from it right away? It makes the process of creating Pull Requests dead-simple, and by doing it that way, everyone knows which code you are referring to right away.

**Comment by walkwizus** [comment]
Thanks ! Next time I do that !

**Comment by walkwizus** [comment]
Hi !

I don't see the modification in the last release, just an update in composer.json and release note. I do the PR ?

Thanks

**Comment by jissereitsma** [comment]
The following comparison shows all differences between 0.12.2 and 0.12.3: https://github.com/yireo/Yireo_Webp2/compare/0.12.2...0.12.3 It includes the semicolon. Could you double-check which version you are using and which files is not confirmed to be modified?
