### ISSUE TITLE
magento 2.4.5 not working after instalation

### ISSUE THREAD

**Issue by michaltrojmiasto** [yireo/Yireo_Webp2#142]
Hello,
Installed on Debian 11, Magento 2.4.5-p1, php 8.1.15, magento2-webp2 0.12.4
- I installed the plugin via composer - no errors.
- I enabled developer mode.
- I disabled "Page Cache" and "Blocks HTML output"
- cache:clean and cache:flush - done
- checked the phpinfo() - WebP Support: enabled 
- pub/ is writable by webserver
- I left the default settings in the admin panel
The plugin doesn't seem to work. Where to look for the cause of the problem?

**Comment by jissereitsma** [comment]
You were pretty specific about all of the steps, but I'm missing the step where you're mentioning that the module itself is enabled. Could you double-check? Also, see the following: https://github.com/yireo/Yireo_Webp2/blob/master/SUPPORT.md

**Comment by michaltrojmiasto** [comment]
I was installing ith instruction on page: https://www.yireo.com/software/magento-extensions/webp2 
There is only:  bin/magento module:enable Yireo_Webp2
I didn't install Yireo_NextGenImages
Now I installed it and it works fine :)

**Comment by jissereitsma** [comment]
Thanks. I'll close this issue for now. Here on GitHub the installation instructions actually mention the enabling of the other supporting module as well. That same text should have been incorporated on the Yireo site, but I'll double-check why this is not the case yet.
