### ISSUE TITLE
update yireo/magento2-next-gen-images

### ISSUE THREAD

**Issue by rommelfreddy** [yireo/Yireo_Webp2#145]
The dependency yireo/magento2-next-gen-images is outdated. 

Current allowed version: 0.3x.
Current available version: 0.4.x

**Comment by jissereitsma** [comment]
Good catch. I've released a new version to bump this right away.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity. Feel free to reopen if needed.
