### ISSUE TITLE
webp images not generated for product gallery image

### ISSUE THREAD

**Issue by shallu2021** [yireo/Yireo_Webp2#147]
I am using Magento 2.4.4 and for frontend, Hyva theme is in use. I have checked that for the product page, Gallery images are not generated webp images.
Yiero nextgenImages version: 0.3.5
webp2 version:0.12.1

**Comment by jissereitsma** [comment]
Could you try upgrading to the latest versions first?

**Comment by shallu2021** [comment]
I have update the both extension
Yiero nextgenImages version: 0.3.18
webp2 version:0.12.5
but now webp images not generated

**Comment by jissereitsma** [comment]
Please understand that there is little for me to gain from maintaining this module. If you are simply just reporting that "it does not work", either I teach you how to debug things with a programming skillset, or start working on different projects. Please eloborate as much as you can on this situation. If you say "images are not generated", it is possible that you haven't enabled anything yet, haven't checked for any of the documentation here, haven't done any of the troubleshooting suggested here, and are simpy doing nothing to help yourself. Please provide details, as if YOU are trying to fix this.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity. If you are still experiencing issues, and need help, please provide more details so that others are indeed able to help.
