### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by web4exposure-org** [yireo/Yireo_Webp2#150]
In the changelog, version 0.13.0 is already released. The last release however, is 0.12.5. 
Please update the latest release to 0.13.0 so composer can update it to the last version without having to use dev-master. (or is there a reason this is not updated?)

**Comment by jissereitsma** [comment]
Whoops, no, it is just that development fell still last couple of months, because of life. I've released 0.13.0 right away.

**Comment by web4exposure-org** [comment]
Thanks!
