### ISSUE TITLE
Hyva\GraphqlViewModel\Model\GraphqlQueryEditor" does not exist  

### ISSUE THREAD

**Issue by Kiwifu** [yireo/Yireo_Webp2#151]
Hi [jissereitsma](https://github.com/jissereitsma)

I am facing an issue : 

bin/magento setup:di:compile
Compilation was started.
Area configuration aggregation... 5/9 [=======>-----]  55% 32 secs 374.0 MiB
In ClassReader.php line 57:
                                                                               
  Impossible to process constructor argument Parameter #0 [ <required> Hyva\G  
  raphqlViewModel\Model\GraphqlQueryEditor $queryEditor ] of Yireo\Webp2\Obse  
  rver\AddUrlWebpToGraphqlQuery class                                          
                                                                               

In GetParameterClassTrait.php line 34:
                                                                         
  Class "Hyva\GraphqlViewModel\Model\GraphqlQueryEditor" does not exist

**Comment by emetik** [comment]
Same Issue for me
Composer installed module version : 0.13.0
Magento 2.4.6-p2
PHP 8.1

**Comment by vncnt-mb** [comment]
Same issue after updating to 0.13 (rollback to 0.12.5 in composer.json solve the issue)
Magento 2.4.6-p1 / PHP 8.2 / Custom theme

**Comment by Kiwifu** [comment]
@emetik @vncnt-mb Thank you so much for you replies,

How to do this?

**Comment by vncnt-mb** [comment]
You can edit your `composer.json` and change the version of this package

<img width="431" alt="Capture d’écran 2023-09-06 à 14 45 05" src="https://github.com/yireo/Yireo_Webp2/assets/48125944/ef4222b6-f82a-42c0-a663-249f017d6db0">

In the screenshot, we indicate to composer that we only want to use version 0.12.5

After this modification, you just need to do a `composer update` and you're done! :)

**Comment by jissereitsma** [comment]
Sorry for this screw up. Further refactoring was actually needed for this, but somebody requested I released all of the code already, while I should have checked for this first. Release 0.13.1 is going to move this Hyva dependency to a separate package https://github.com/yireo/Yireo_Webp2ForHyva instead and therefore fix this.
