### ISSUE TITLE
Undefined property: Exception::$description

### ISSUE THREAD

**Issue by web4exposure-org** [yireo/Yireo_Webp2#152]
I'm having an issue which is causing a server error for the whole page. This is happening on some pages, but not all pages. Most of the webp images are generated, although some pages are not loading because of the following error:

`{"0":"Warning: Undefined property: Exception::$description in \/var\/www\/html\/vendor\/yireo\/magento2-webp2\/Convertor\/ConvertWrapper.php on line 56"`

Here is the line:
`$this->logger->debug($e->getMessage() . ' - ' . $e->description, $e->getTrace());`

As far as I know, Exception::$description is not such a thing.

**Comment by jissereitsma** [comment]
See also https://github.com/yireo/Yireo_Webp2/issues/153 this will be fixed in the hour
