### ISSUE TITLE
Unsupported image format GD2 and .svg

### ISSUE THREAD

**Issue by onepack** [yireo/Yireo_Webp2#156]
Is this issue related to the Yireo module trying to convert the .svg to .webp via the GD2 adapter?  (see under)
The SVG images work on the website and are visible for visitors.

Nextgen Module version | 0.3.10
WebP Module version | 0.12.4

Magento: 2.4.4-p3
PHP: 8.1.18

{"0":"Unsupported image format. File: \/data\/web\/.deployer\/production\/releases\/webshop\/pub\/media\/catalog\/category\/Icon_categoryimage.svg","1":"#1 Magento\\Framework\\Image\\Adapter\\Gd2->open() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#2 Magento\\Framework\\Image\\Adapter\\Gd2\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#3 Magento\\Framework\\Image\\Adapter\\Gd2\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#4 Magento\\Framework\\Image\\Adapter\\Gd2\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/Image\/Adapter\/Gd2\/Interceptor.php:23]\n#5 Magento\\Framework\\Image\\Adapter\\Gd2\\Interceptor->open() called at [vendor\/magento\/module-cms\/Model\/Wysiwyg\/Images\/Storage.php:710]\n#6 Magento\\Cms\\Model\\Wysiwyg\\Images\\Storage->resizeFile() called at [vendor\/magento\/module-cms\/Model\/Wysiwyg\/Images\/Storage.php:763]\n#7 Magento\\Cms\\Model\\Wysiwyg\\Images\\Storage->resizeOnTheFly() called at [vendor\/magento\/module-cms\/Controller\/Adminhtml\/Wysiwyg\/Images\/Thumbnail.php:41]\n#8 Magento\\Cms\\Controller\\Adminhtml\\Wysiwyg\\Images\\Thumbnail->execute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#9 Magento\\Cms\\Controller\\Adminhtml\\Wysiwyg\\Images\\Thumbnail\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#10 Magento\\Cms\\Controller\\Adminhtml\\Wysiwyg\\Images\\Thumbnail\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#11 Magento\\Cms\\Controller\\Adminhtml\\Wysiwyg\\Images\\Thumbnail\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Cms\/Controller\/Adminhtml\/Wysiwyg\/Images\/Thumbnail\/Interceptor.php:23]\n#12 Magento\\Cms\\Controller\\Adminhtml\\Wysiwyg\\Images\\Thumbnail\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:111]\n#13 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:151]\n#14 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#15 Magento\\Cms\\Controller\\Adminhtml\\Wysiwyg\\Images\\Thumbnail\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#16 Magento\\Cms\\Controller\\Adminhtml\\Wysiwyg\\Images\\Thumbnail\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:145]\n#17 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#18 Magento\\Cms\\Controller\\Adminhtml\\Wysiwyg\\Images\\Thumbnail\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#19 Magento\\Cms\\Controller\\Adminhtml\\Wysiwyg\\Images\\Thumbnail\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Cms\/Controller\/Adminhtml\/Wysiwyg\/Images\/Thumbnail\/Interceptor.php:32]\n#20 Magento\\Cms\\Controller\\Adminhtml\\Wysiwyg\\Images\\Thumbnail\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:245]\n#21 Magento\\Framework\\App\\FrontController->getActionResponse() called at [vendor\/magento\/framework\/App\/FrontController.php:212]\n#22 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:147]\n#23 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#24 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#25 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#26 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#27 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#28 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]\n#29 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:30]\n","url":"\/admin_zg4dyg\/cms\/wysiwyg_images\/thumbnail\/file\/SWNvbl9rYWJlbGRyYWFkLnN2Zw--\/","script_name":"\/index.php","report_id":"7fadbdc5cb0e930c39399894723078508e81c10c659bfa0fbeb41db40263a91b"}

**Comment by onepack** [comment]
Thank you! I wanted to make sure. Will do as you suggested.

**Comment by jissereitsma** [comment]
Reference https://github.com/yireo/Yireo_NextGenImages/blame/master/CHANGELOG.md#fixed-1
