### ISSUE TITLE
Generating webp image in pagebuilder banner

### ISSUE THREAD

**Issue by bar-dom** [yireo/Yireo_Webp2#158]
Hello, the module was installed on magento ver. 2.4.6-p1 with hyva template. The webp images generate correctly, but for banners created in pagebuilder the images remain in the original format. 

![image](https://github.com/yireo/Yireo_Webp2/assets/71754720/8e6835da-fbae-4c05-bd94-65c6bb2259ae)

I understand that this is related to the HTML structure, but I am wondering if, in addition to changing the HTML structure of the banner, there is a way to detect and convert the image in the banner to webp format ?

**Comment by Bashev** [comment]
Switching Convert CSS Background to "Yes" will be enough

![image](https://github.com/yireo/Yireo_Webp2/assets/1854269/fb76d712-a843-4378-adf7-d09371980623)

**Comment by bar-dom** [comment]
@Bashev Thanks for the solution.
