### ISSUE TITLE
Extension breaks Varnish FPC

### ISSUE THREAD

**Issue by jonashrem** [yireo/Yireo_Webp2#16]
On a freshly installed magento2 store (with demo data), this extension breaks Varnish FPC (front page is not cache able any longer).

Except from this module I only had smile/elasticsuite and mageplaza/magento-2-german-language-pack:dev-master installed.

**Comment by jissereitsma** [comment]
Thanks for reporting an issue. Could you explain what you mean with "breaking Varnish"? What is the end result of this?

What I can say is that a Magento extension could "disable" the Full Page Cache using a XML layout statement `cacheable=false`. However, this extension is not doing so in any way. The Full Page Cache is still available and therefore, the page is cachable by Varnish.

**Comment by jonashrem** [comment]
Hello,

the page is cached anymore by varnish and is getting fetched from the webserver (like with cacheable=false)

If you want, I can try to create a testing environment with this behavior.

**Comment by jissereitsma** [comment]
I've just run a test with a Docker-based Varnish 6 instance in a clean Magento 2 environment with only the Yireo_WebP extension installed. It works fine in my case and the FPC is enabled everywhere where it should (CMS-pages, product pages, category pages).

Sorry, I can't confirm your issue. It does not seem to be a generic issue, as of yet.

**Comment by jonashrem** [comment]
I'll try to reproduce this again without the other modules and check again.

**Comment by jissereitsma** [comment]
I'm closing this issue for now. Feel free to re-open if you think this issue still applies to the extension itself.
