### ISSUE TITLE
Can not upgrade to magento 2.4.7.

### ISSUE THREAD

**Issue by richardreen** [yireo/Yireo_Webp2#163]
Getting the following error while tried to upgrade to 2.4.7.

  Problem 1
    - Root composer.json requires magento/product-community-edition 2.4.7 -> satisfiable by magento/product-community-edition[2.4.7].
    - Root composer.json requires yireo/magento2-webp2 ^0.12.5 -> satisfiable by yireo/magento2-webp2[0.12.5].
    - magento/product-community-edition 2.4.7 requires magento/framework 103.0.7 -> satisfiable by magento/framework[103.0.7].
    - yireo/magento2-webp2 0.12.5 requires psr/log ^1.0 -> satisfiable by psr/log[1.0.0, ..., 1.1.4].
    - You can only install one version of a package, so only one of these can be installed: psr/log[1.0.0, ..., 1.1.4, 2.0.0, 3.0.0].
    - magento/framework 103.0.7 requires psr/log ^2 || ^3 -> satisfiable by psr/log[2.0.0, 3.0.0].
    - Conclusion: don't install psr/log 3.0.0 (conflict analysis result)

Is saw that psr/log dependancies where change but I got stuck in version 12.5. Even with an re-install of this module results in version 12.5.

I changed the psr/log manual but I keep getting this error.

**Comment by jissereitsma** [comment]
Thanks for posting. Version 0.13.5 fixes this issue: https://github.com/yireo/Yireo_Webp2/blob/master/CHANGELOG.md

Note that 12.5 does not exist and 0.12.5 is not compatible with Magento 2.4.7.

**Comment by richardreen** [comment]
The hightest  available version is 0.13.4…and no 0.13.5

- Root composer.json requires yireo/magento2-webp2 ^0.13.5, found yireo/magento2-webp2[dev-renovate/configure, dev-master, 0.0.1, ..., 0.13.4] but it does not match the constraint.

- Upgrading yireo/magento2-webp2 (0.12.5 => 0.13.4): Extracting archive

**Comment by jissereitsma** [comment]
Thanks. It seems the new version was never pushed to Packagist properly. It now is. Note however that if you would be upgrading your own project, version 0.13.4 was the highest version moments ago, not 0.12.5. I trust that - now 0.13.5 is pushed - you can upgrade to that version.
