### ISSUE TITLE
GraphQL dependencies

### ISSUE THREAD

**Issue by davekleijn** [yireo/Yireo_Webp2#166]
Hello,

I am using the Yireo_Webp2 module in my Magento 2 installation. Currently, the module has dependencies on GraphQL. However, I deleted all GraphQL dependencies. Same solution as in [yireo/magento2-replace-tools](https://github.com/yireo/magento2-replace-tools).

Could you please review the module and remove any unnecessary GraphQL dependencies to ensure it works seamlessly for installations that utilize magento2-replace-tools?

```
bin/magento setup:di:compile
Compilation was started.
Area configuration aggregation... 5/9 [===============>------------]  55% 45 secs 218.0 MiB
In ClassReader.php line 57:

  Impossible to process constructor argument Parameter #0 [ <required> Magento\CatalogGraphQl\Model\Resolver\Product\MediaGallery\Url $urlResolver ] of Yireo\Webp2\GraphQl\Resolver\WebpUrl class


In GetParameterClassTrait.php line 41:

  Class "Magento\CatalogGraphQl\Model\Resolver\Product\MediaGallery\Url" does not exist
```

Thank you!

Best regards,
Dave

**Comment by jissereitsma** [comment]
Good point. I have now split up the GraphQL support into a separate module here: https://github.com/yireo/Yireo_Webp2GraphQl

**Comment by davekleijn** [comment]
Hi @jissereitsma,

DI compile is working now.

Thank you!
