### ISSUE TITLE
Support for LazyLoad

### ISSUE THREAD

**Issue by hammockvienna** [yireo/Yireo_Webp2#17]
Hi,

according to https://web.dev/use-lazysizes-to-lazyload-images/ we would have to change the tags within https://github.com/yireo/Yireo_Webp2/blob/master/view/frontend/templates/picture.phtml from srcset to data-srcset. 

Within the list.phtml for the category lists we would also have to change the <img> tag from src to data-src. => in that moment the module itself is not working anymore and the picture tag is not generated.

I guess it has something todo with the module function afterGetOutput line 88 (https://github.com/yireo/Yireo_Webp2/blob/master/Plugin/ReplaceTags.php#88). There i have seen a regex which searches for the src with the image tag. 

When i change the regex from src to data-src lazy load is working fine on all category list pages.

From my understanding it would not be working on all the other pages where we dont have the data-src within the html (for example a standard cms page). So i think it would be necessary to enhance regex so both data-src and src would be machted.

changed it from
`$regex = '/<([^<]+)\ src=\"([^\"]+)\.(png|jpg|jpeg)([^>]+)>/mi';`
to
$regex = '/<([^<]+)\ (data-src|src)=\"([^\"]+)\.(png|jpg|jpeg)([^>]+)>/mi';

and in order to find the right groups within the regex
`$imageUrl = $matches[2][$index][0] . '.' . $matches[3][$index][0];`
to
`$imageUrl = $matches[3][$index][0] . '.' . $matches[4][$index][0];`

Question
1.) Is there something else to change?
2.) is there any plan to make the module also compatible with lazyload out of the box? I guess thats really important.

**Comment by hammockvienna** [comment]
any news on that?

**Comment by jissereitsma** [comment]
Sorry for the delay. I'm running many open source projects and this is just one of them, so unless others are chiming in to contribute, there is no response guaranteed. To answer your questions:

1) From the top of my mind, I wouldn't know any other places to modify to make your custom solution work. 

2). No, unfortunately not. Lazyload is not something that is required by everyone, plus there are numerous other lazyloading techniques and they would all require hacks in the original code of this WebP extension. The logic here is that we want clean coding, and not hacks upon hacks. The WebP extension has a single purpose and therefore is clean - adding anything else would break that purpose and make the extension ugly.

A counter question to you would be how you are implementing the lazyload functionality yourself. If it is through a theming modification, you would still need a module to overwrite the PHP code of this WebP extension. If it is through a new module (say `HelloWorld_Lazyload`) then it would be bad coding to add WebP-required hacks in there. It would make more sense to allow for yet a third module `HelloWorld_LazyLoadWebPCompatibility` to specifically override those things of the WebP-extension that are required by the Lazyload-module.

Please note that changing `srcset` to `data-srcset` is a solution proposed by the blog you mentioned, but it is by no means a web-standard and will therefore definitely be part of this extension. It will break all other sites, that simply rely on the required HTML that works in the browser.

This really sounds like custmization work, than general behaviour.

**Comment by jissereitsma** [comment]
I'll close this issue for now. Feel free to re-open if you still have questions or issues here.
