### ISSUE TITLE
(maybe project specific) Cart - TypeError: Yireo\Webp2\Plugin\AddCspInlineScripts::afterToHtml

### ISSUE THREAD

**Issue by sfritzsche** [yireo/Yireo_Webp2#170]
Magento version: 2.4.7-p2
Module version: 0.14.1
Page: /checkout/cart/

Error message: TypeError: Yireo\Webp2\Plugin\AddCspInlineScripts::afterToHtml(): Return value must be of type string, null returned in /path/to/my/magento/vendor/yireo/magento2-webp2/Plugin/AddCspInlineScripts.php:21

Further information:

Name of the associated layout block: content_schedule_block0
Found method "\Magento\Framework\View\Layout\ScheduledStructure\Helper::scheduleStructure" that uses **"_schedule_block"** as part of name.

Recommendation: 

The plugin should be converted into an event observer (view_block_abstract_to_html_after) and handle the transfer from null.

**Comment by jissereitsma** [comment]
This is simply the lack of type hinting of Magento in the past, causing issues. A refactoring from a DI plugin to an event observer seems a bit much to just fix that type cast. Why did you recommend that?

The latest version 0.14.2 now fixes this.
