### ISSUE TITLE
Uncaught Error: Class 'WebPConvert\WebPConvert' not found

### ISSUE THREAD

**Issue by Eddcapone** [yireo/Yireo_Webp2#21]
I installed the extension, but I get the error mentioned in the title.

I am using Magento 2.3.4

**Comment by jissereitsma** [comment]
Are you sure you installed this module using composer?

**Comment by Eddcapone** [comment]
No, I just downloaded this git repository. How can I install it without using composer?

**Comment by jissereitsma** [comment]
Indeed, this extension has dependencies. But that dependency (`rosell-dk/webp-convert`) might yet have other dependencies again. Tracking all those dependencies (with the right corresponding to Magento versions and PHP versions) manually is a nightmare. This is why composer was developed. And this is also the reason why installing extensions with composer has become the only best practice for managing Magento modules (including the core). I really can't recommend anything else.

**Comment by Eddcapone** [comment]
Thank you for your answer, this really makes sense and I never thought about it this way.
