### ISSUE TITLE
Settings for cwebp path 

### ISSUE THREAD

**Issue by pamiec** [yireo/Yireo_Webp2#23]
I am looking for the setting to change the path for the cweb bin (Webp2). 
Unfortunately I can't see anything in the backend-settings of Yireo and nothing in the extension files.

![webp2](https://user-images.githubusercontent.com/55427697/74228105-17814100-4cc0-11ea-9f2e-333f9b2ca7ca.png)

**Comment by jissereitsma** [comment]
There is none. Since some time now, this extension relies on the library rosell-dk/webp-convert which ships with its own binaries.

**Comment by jissereitsma** [comment]
I'll close this issue for now. Feel free to re-open if you still have questions or issues here.
