### ISSUE TITLE
Feature request: enable Native lazy-loading for the web

### ISSUE THREAD

**Issue by onepack** [yireo/Yireo_Webp2#29]
Add the option in the settings to enable the new standard for lazy loading of images.
loading="lazy"

"Enable Lazy loading webp images"
https://caniuse.com/#search=loading%3D%22lazy%22

https://web.dev/native-lazy-loading/?utm_source=lighthouse&utm_medium=devtools

**Comment by jissereitsma** [comment]
This feature is now included in version 0.6.0.
