### ISSUE TITLE
Image not showing if my image URL is third party

### ISSUE THREAD

**Issue by hardiklinksture** [yireo/Yireo_Webp2#30]
Magento version **2.3.4**
PHP version **7.2.19**
Extension verison **0.6.0**

My html is: `<img src="https://pci.usd.de/compliance/4121-F2FF-3B58-3710-F482-05A4/seal_ctv_80.png" alt="" width="40px">`
If my image src is the third party then it will be showing the error like below

Showing error
```
1 exception(s):
Exception #0 (Magento\Framework\View\Asset\File\NotFoundException): /var/www/html/magento/pub/compliance/4121-F2FF-3B58-3710-F482-05A4/seal_ctv_80.png is not found

Exception #0 (Magento\Framework\View\Asset\File\NotFoundException): /var/www/html/magento/pub/compliance/4121-F2FF-3B58-3710-F482-05A4/seal_ctv_80.png is not found
#1 Yireo\Webp2\Image\Convertor->convert('https://pci.usd....', 'https://pci.usd....') called at [vendor/yireo/magento2-webp2/Plugin/ReplaceTags.php:107]
#2 Yireo\Webp2\Plugin\ReplaceTags->afterGetOutput(&Magento\Framework\View\Layout\Interceptor#0000000064c2a13100000000193782fc#, '\n\n<script type="...') called at [vendor/magento/framework/Interception/Interceptor.php:146]
#3 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#4 Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', array(), array(array('yireo_webp2_repl...', 'layout-model-cac...'))) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:494]
#5 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#6 Magento\Framework\View\Result\Page->render(&Magento\Framework\App\Response\Http\Interceptor#0000000064c2a3c900000000193782fc#) called at [vendor/magento/framework/View/Result/Layout.php:171]
#7 Magento\Framework\View\Result\Layout->renderResult(&Magento\Framework\App\Response\Http\Interceptor#0000000064c2a3c900000000193782fc#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#8 Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#0000000064c2a3c900000000193782fc#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#9 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Response\Http\Interceptor#0000000064c2a3c900000000193782fc#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#10 Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#0000000064c2a3c900000000193782fc#), array(array('result-messages', 'FishPig_WordPres...', 'result-builtin-c...', 'result-varnish-c...'))) called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:130]
#11 Magento\Framework\View\Result\Page\Interceptor->renderResult(&Magento\Framework\App\Response\Http\Interceptor#0000000064c2a3c900000000193782fc#) called at [vendor/magento/framework/App/Http.php:120]
#12 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#13 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#14 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000064c2a3d200000000193782fc#) called at [index.php:39]

```

**Comment by jissereitsma** [comment]
Do you have debugging enabled?

**Comment by hardiklinksture** [comment]
Yes debugging is enabled


debug.log` [2020-03-18 08:06:54] main.ERROR: /var/www/html/mage234/pub/compliance/4121-F2FF-3B58-3710-F482-05A4/seal_ctv_80.png is not found [] []`

system.log `[2020-03-18 08:06:54] main.ERROR: /var/www/html/mage234/pub/compliance/4121-F2FF-3B58-3710-F482-05A4/seal_ctv_80.png is not found [] []`

**Comment by jissereitsma** [comment]
So the exception disappears with debugging disabled.

**Comment by hardiklinksture** [comment]
If we disable debugging then it will generate the report. check the below report.

`{"0":"\/var\/www\/webroot\/ROOT\/pub\/compliance\/4121-F2FF-3B58-3710-F482-05A4\/seal_ctv_80.png is not found","1":"#1 Yireo\\Webp2\\Image\\Convertor->convert('https:\/\/pci.usd....', 'https:\/\/pci.usd....') called at [vendor\/yireo\/magento2-webp2\/Plugin\/ReplaceTags.php:107]\n#2 Yireo\\Webp2\\Plugin\\ReplaceTags->afterGetOutput(&Magento\\Framework\\View\\Layout\\Interceptor#0000000064eb000e000000004f550337#, '          <scrip...') called at [vendor\/magento\/framework\/Interception\/Interceptor.php:146]\n#3 Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#4 Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', array(), array(array('yireo_webp2_repl...', 'layout-model-cac...'))) called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:494]\n#5 Magento\\Framework\\View\\Layout\\Interceptor->getOutput() called at [vendor\/magento\/framework\/View\/Result\/Page.php:258]\n#6 Magento\\Framework\\View\\Result\\Page->render(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000064eb02fb000000004f550337#) called at [vendor\/magento\/framework\/View\/Result\/Layout.php:171]\n#7 Magento\\Framework\\View\\Result\\Layout->renderResult(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000064eb02fb000000004f550337#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#8 Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', array(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000064eb02fb000000004f550337#)) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#9 Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000064eb02fb000000004f550337#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#10 Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', array(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000064eb02fb000000004f550337#), array(array('result-messages', 'FishPig_WordPres...', 'result-builtin-c...', 'result-varnish-c...'))) called at [generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php:130]\n#11 Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(&Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000064eb02fb000000004f550337#) called at [vendor\/magento\/framework\/App\/Http.php:120]\n#12 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#13 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#14 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#0000000064eb02e2000000004f550337#) called at [pub\/index.php:40]\n","url":"\/checkout\/cart\/","script_name":"\/index.php","report_id":"7f4cc14105fc74d50b3318cf9a5aa943effc14c9620243f6a9704ff7ea32eaae"}`

**Comment by jissereitsma** [comment]
Could you upgrade to 0.6.1 to see if this fixes things?

**Comment by hardiklinksture** [comment]
Yes, now it's working fine.
