### ISSUE TITLE
WebP not replacing image tags on Ajax call

### ISSUE THREAD

**Issue by hypershopbv** [yireo/Yireo_Webp2#32]
Hi,

First of all, great extension!

We are using an Ajax Layered Navigation in many our projects. The image tags will not be replaced if the content is updated by an Ajax call. Is there a way to support this?

**Comment by jissereitsma** [comment]
Most likely, the extension in question is generating images as part of PHTML templates (which should be picked up by our extension) or generating images in JavaScript. If this is in JavaScript, the JavaScript of that extension needs to be modified. Either way, somebody needs to investigate it. Perhaps we can get closer to an actual solution if we know which extension it actually is, plus if there is a demo of it.

**Comment by hypershopbv** [comment]
Hi Jisse,

Thanks for your quick reply.
The extension in question is the Improved Layered Navigation by Amasty. This extension has the option to use Ajax filters, so when clicking a filter the complete page will not be reloaded.

Does this give you enough information to go forward? Otherwise you can contact me directly, so we can discuss this further.

**Comment by jissereitsma** [comment]
It is a bit much to pick up on this voluntarily, because I don't see right away a shortcoming of this extension, but perhaps a flaw in the design of the other module. I'm happy to pick this up as a custom assignment though - ping me at Duchento Slack or send me a mail, so we can see what steps can be made.

**Comment by hypershopbv** [comment]
Hi Jisse,

I just sent you an e-mail. I will close this issue for now.
