### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by NafeesKhabir** [yireo/Yireo_Webp2#35]
After Running Following command `composer require yireo/magento2-webp2`

I've received below in my terminal 

>composer require yireo/magento2-webp2
Using version ^0.7.1 for yireo/magento2-webp2
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yireo/magento2-webp2 ^0.7.1 -> satisfiable by yireo/magento2-webp2[0.7.1].
    - yireo/magento2-webp2 0.7.1 requires magento/framework ^101.0.1|^101.1|^102.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by jissereitsma** [comment]
Indeed, this could happen. What is your Magento version?

**Comment by NafeesKhabir** [comment]
2.3.4

**Comment by jissereitsma** [comment]
And can you confirm that Magento is installed via composer? What does the command `composer show | grep magento/framework` show you?

**Comment by NafeesKhabir** [comment]
magento/framework                                                 102.0.3 
magento/framework-amqp                                            100.3.3 
magento/framework-bulk                                            100.3.3 
magento/framework-message-queue                                   100.3.3

**Comment by jissereitsma** [comment]
Thanks. So this strange and I don't the solution for this. Your error contains the following: `yireo/magento2-webp2 0.7.1 requires magento/framework ^101.0.1|^101.1|^102.0` which is suggesting that our extension requires a Magento framework version that is not installed in your system. Nonetheless, your Magento framework is of version 102.0.3 which matches with the `^102.0` part in the composer requirement. As of yet, I don't know how to proceed. I have just now installed this extension 0.7.1 under a demo Magento 2.3.3 environment and there it works without issues.

**Comment by NafeesKhabir** [comment]
Gave error but found it installed

**Comment by jissereitsma** [comment]
Then something else must have been the problem. Because if composer gives an error, it does not install things. Perhaps you ran the command in the wrong folder?
