### ISSUE TITLE
Nativ lazyloading is not workung with the picture element

### ISSUE THREAD

**Issue by frostblogNet** [yireo/Yireo_Webp2#36]
Hello @jissereitsma 

thanks for this amazing extension. But I ran into an issue and want to discuss this with you. Maybe you know a smart solution for that.

It think nativ lazy loading which you added into your extension with a picture element is not working.

The problem here is that modern browsers like chrome is not using the image tag inside the picture element. They will use the webp image from the source map instead. Due to this issue the nativ lazy loading is not working.

Only older browsers like i.e. will recognize the loading="lazy" attribute but they are unable to use it.

So in my opinion this is not working. 

Just to make this clear the problem is not in your extension, I think it is a design error of the picture element. 

But please let me know what are your thoughts.

Thanks 

Jens

**Comment by jissereitsma** [comment]
First of all, can you confirm that the `loading="lazy"` attribute is in the HTML code? Just to check. If it is there, then according to the specifications, it should work. For reference, I read through this and there seems to be nothing wrong with it: https://web.dev/native-lazy-loading/ Actually, the specification of `picture` says that most `source` attributes will be borrowed from `img`, so I don't know why this would not be working for the lazy loading. That being said, the lazy loading feature is new, so it might be giving issues in browsers.

Cutting short the discussion, I will not be able to add a fix unless that fix is documented as a known issue with a known work-around.

**Comment by frostblogNet** [comment]
Thanks for your fast response and the reference. It turns out that google lighthouse fooled me a bit. So sorry for the false positv here and thanks for your work.
