### ISSUE TITLE
Not working on Magento 2.3.5-p1 ?

### ISSUE THREAD

**Issue by oviliz** [yireo/Yireo_Webp2#37]
Hi guys, I'm on Magento 2.3.5 and using PHP 7.3. This is a fresh install with one product and no other 3rd party extensions (except for those Magento spams us with...).
![image](https://user-images.githubusercontent.com/73616/83461660-34a17180-a461-11ea-914f-9a31c4b13b3f.png)

I've cleared all cache (Magento + server + browser) and I'm simply inspecting the element in the browser but I'm not getting to see any WebP references.
```
<div class="fotorama__stage__shaft fotorama__grab" tabindex="0" data-gallery-role="stage-shaft" style="transition-duration: 0ms; transform: translate3d(0px, 0px, 0px); margin-left: 0px; width: 707px;">
	<div class="fotorama__stage__frame fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img fotorama__active" aria-hidden="false" data-active="true" style="left: 0px;" href="/media/catalog/product/cache/0a8c1a7b1e3be62f3c96d7079742ca7a/a/r/ar12.jpg"><img src="/media/catalog/product/cache/0a8c1a7b1e3be62f3c96d7079742ca7a/a/r/ar12.jpg" alt="Round Arch" class="fotorama__img" aria-hidden="false"></div><div class="fotorama__stage__frame fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img" aria-hidden="true" style="left: -709px;" href="/media/catalog/product/cache/0a8c1a7b1e3be62f3c96d7079742ca7a/a/r/ar12_1.jpg"><img src="/media/catalog/product/cache/0a8c1a7b1e3be62f3c96d7079742ca7a/a/r/ar12_1.jpg" alt="Round Arch" class="fotorama__img" aria-hidden="false"></div><div class="fotorama__stage__frame fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img" aria-hidden="true" style="left: 709px;" href="/media/catalog/product/cache/0a8c1a7b1e3be62f3c96d7079742ca7a/a/r/ar12_2.jpg"><img src="/media/catalog/product/cache/0a8c1a7b1e3be62f3c96d7079742ca7a/a/r/ar12_2.jpg" alt="Round Arch" class="fotorama__img" aria-hidden="false"></div>
</div>
```

I wonder if this is to do with the "Fotorama" discussion at https://github.com/yireo/Yireo_Webp2/issues/26
From my code (Luma theme), it looks like Magento comes with that out of the box, right?

**Comment by jissereitsma** [comment]
Please see the note here: https://github.com/yireo/Yireo_Webp2/blob/master/USAGE.md

**Comment by oviliz** [comment]
@jissereitsma , so there's no way this can be used without replacing default Fotorama. The recommended Notorama though comes with a note that "is currently considered unstable and **should not be used outside of development**" so that's basically useless as is.
Will eventually try this again with a different production usable theme if that replaces Fotorama. Thank you.

**Comment by jissereitsma** [comment]
Yes, there is a small notice of the Notorama developer that basically shows he is not a huge marketeer and simply wants things to be open-source, not freebie.

Fotorama is bad for performance, not extensible and outdated. And not compatible with WebP unless you are rewriting its JavaScript.
