### ISSUE TITLE
W3C Validator attribute alt not allowed on element picture at this point.

### ISSUE THREAD

**Issue by gjportegies** [yireo/Yireo_Webp2#39]
The [w3c validator](https://validator.w3.org/) is showing me errors because the picture element itself should not contain an alt attribute. Only the img element inside the picture element should have an alt attribute.

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture
- https://developers.google.com/web/fundamentals/design-and-ux/responsive/images#art_direction_in_responsieve_afbeeldingen_met_picture

![Schermafbeelding 2020-06-13 om 13 51 50](https://user-images.githubusercontent.com/6707410/84568346-20257900-ad7f-11ea-8782-ddc237bdf80b.png)

**Comment by jissereitsma** [comment]
Closed with https://github.com/yireo/Yireo_Webp2/pull/40
