### ISSUE TITLE
Does not works with the CentOS 6 becuase of WebP support not enabled for PHP GD library.

### ISSUE THREAD

**Issue by ashoklinksture** [yireo/Yireo_Webp2#47]
I have installed Magento version 2.3.5-p1 on CentOS 6 and installed this extension but it does not work. Then i contact to my server support team and they send reply as below:

RE: WebP - Webp doe not appear to be supported on Centos 6, which is what the server you are using is running, theres no way to change this, we would need to migrate the entire site to one of our other servers. Webp is part of the PHP-GD library and when enabled (which i have done) it doesn't appear on the list of modules, this has been discussed on cpanel forums 
https://support.cpanel.net/hc/en-us/articles/360051429314-WebP-support-not-enabled-in-GD​

So is there any other way to achieve this?

**Comment by jissereitsma** [comment]
No. This Magento extension relies on either the binaries to be working or the PHP support to be there. If neither works, it does not work.
