### ISSUE TITLE
preg_match_all can't detect 2 img tags rendered next to each other. 

### ISSUE THREAD

**Issue by toanthree** [yireo/Yireo_Webp2#48]
Thanks for the great module. I have installed the module and it works fine for most of the case, but not with the case there are 2 img tags that are rendered next to each other. 

Here is the HTML that the layout rendered:
```
<img class="pagebuilder-mobile-hidden" src="desktop_image.jpg" data-element="desktop_image">
<img class="pagebuilder-mobile-only" src="mobile_image.jpg" data-element="mobile_image">
```

preg_match_all only matches the first img tag while it should match both of them. See [here](https://prnt.sc/uo51va)

I know there is a hack workaround by adding a span tag between the 2 images, but these HTML markups are generated by the page builder extension.

Do you think we can detect this case and fix it in the extension?

**Comment by toanthree** [comment]
Hi @jissereitsma ,

I've created a PR for fixing the issue that I found here #49 . Can you help me review it?

Thanks,
Toan

**Comment by jissereitsma** [comment]
Hi Toan, many thanks. I've got this added on my todo list, but I will not be able to look at it in the upcoming 2 weeks because of a conference Reacticon we're organizing. But right after, I'll look into this.

**Comment by jissereitsma** [comment]
I've done a couple of tests here, and it looks solid. Many thanks! I will merge your PR into the code base. However, I'm in the middle of refactoring the module to become more generic. So it will take some time before the feature is released.
