### ISSUE TITLE
Exclude for some types

### ISSUE THREAD

**Issue by gewaechshaus** [yireo/Yireo_Webp2#53]
Hi @jissereitsma,

many thanks for providing another clean and good module. I've got a question: what is the best way to exclude images from being replaced with the picture tag and keep the original img tag? In this case, we got a site running the Weltpixel/ Owl-based slider which renders the img tag with data-src-mobile and data-src-desktop attributes. 

Cheers,
Jan

**Comment by jissereitsma** [comment]
Did you see the following? https://github.com/yireo/Yireo_Webp2/blob/master/FAQ.md (search for "webp_skip")

**Comment by gewaechshaus** [comment]
Hey @jissereitsma, 
many thanks - for sure I did take a look at the FAQ, but skipped the section when as I read the headline. I had to do a Strg + F to find it. Maybe it would make sense to move it to an own section with a related headline. We are moving too fast those days.

Cheers,
Jan

**Comment by gewaechshaus** [comment]
@jissereitsma - in this case there's no explicit layout handle available. Maybe it would make sense to introduce a css class which makes a possible to skip elements directly in a template.

**Comment by gewaechshaus** [comment]
I made a quick & dirty fix by overwriting the template in a local theme. This could easily be used as a base to do the same with a css class like "web_skip". You can find the GIST here:
https://gist.github.com/gewaechshaus/0071b58d8eccf0f5692ab51af2b9975b

**Comment by jissereitsma** [comment]
Thanks. This sounds like a nice solution. I'll dive into it soon.
