### ISSUE TITLE
Error when compiling new version 0.9.2

### ISSUE THREAD

**Issue by magentox** [yireo/Yireo_Webp2#58]
I am sorry to seem annoying but when compiling I am getting an error on composer not seen before this new version:

**In ClassReader.php line 45:**

```
Impossible to process constructor argument Parameter #0 [ <required> Yireo\Webp2
\Browser\BrowserSupport $browserSupport ] of Yireo\NextGenImages\Plugin\CorrectI
magesInAjaxResponse class

```

**In ClassReader.php line 34:**

`Class Yireo\Webp2\Browser\BrowserSupport does not exist`

**Comment by CalzaFino** [comment]
I am getting the same error running compilation

> I am sorry to seem annoying but when compiling I am getting an error on composer not seen before this new version:
> 
> **In ClassReader.php line 45:**
> 
> ```
> Impossible to process constructor argument Parameter #0 [ <required> Yireo\Webp2
> \Browser\BrowserSupport $browserSupport ] of Yireo\NextGenImages\Plugin\CorrectI
> magesInAjaxResponse class
> ```
> 
> **In ClassReader.php line 34:**
> 
> `Class Yireo\Webp2\Browser\BrowserSupport does not exist`

**Comment by jissereitsma** [comment]
Thanks for keeping up with this. My personal life is a bit too busy, and I was still trying to push this new release, even though the CI system seems to be not working properly. Could you see if version 0.0.4 of the NextGenImages module is fixing this? A simple `composer update` should do the job here.

**Comment by magentox** [comment]
Unfortunately it is not possible to update yireo/magento2-next-gen-images from 0.0.2 to 0.0.4 because of composer.json requirements.

I am getting this error on composer:

**Your requirements could not be resolved to an installable set of packages.**
```
  Problem 1
    - yireo/magento2-webp2 0.9.2 requires yireo/magento2-next-gen-images ^0.0.2 -> satisfiable by yireo/magento2-next-gen-images[0.0.2] but these conflict with your requirements or minimum-stability.
    - yireo/magento2-webp2 0.9.2 requires yireo/magento2-next-gen-images ^0.0.2 -> satisfiable by yireo/magento2-next-gen-images[0.0.2] but these conflict with your requirements or minimum-stability.
    - yireo/magento2-webp2 0.9.2 requires yireo/magento2-next-gen-images ^0.0.2 -> satisfiable by yireo/magento2-next-gen-images[0.0.2] but these conflict with your requirements or minimum-stability.
    - Installation request for yireo/magento2-webp2 ^0.9.2 -> satisfiable by yireo/magento2-webp2[0.9.2].

Installation failed, reverting ./composer.json to its original content.
```

**Comment by jissereitsma** [comment]
@magentox This was indeed a restriction too narrow when dealing with minimum-stability settings. In a clean environment, I'm now able to run `composer require yireo/magento2-webp2` without issues, which installs the WebP2 extension 0.9.3 and `yireo/magento2-next-gen-images` 0.0.4. Does that work for you too?

**Comment by CalzaFino** [comment]
I am able to install WebP2 0.9.0 and Next Gen Images 0.0.4 but O get the same error on compilation.

**Comment by jissereitsma** [comment]
Thanks for the update. Could you run the following commands to verify the existence of the class `BrowserSupport`?
```bash
grep -r Browser vendor/yireo/magento2-next-gen-images
grep -r Browser vendor/yireo/magento2-webp2
```
And could you copy and paste the exact output here?

**Comment by CalzaFino** [comment]
~/public_html$ grep -r Browser vendor/yireo/magento2-next-gen-images
vendor/yireo/magento2-next-gen-images/Plugin/CorrectImagesInAjaxResponse.php:use Yireo\NextGenImages\Browser\BrowserSupport;
vendor/yireo/magento2-next-gen-images/Plugin/CorrectImagesInAjaxResponse.php:     * @var BrowserSupport
vendor/yireo/magento2-next-gen-images/Plugin/CorrectImagesInAjaxResponse.php:     * @param BrowserSupport $browserSupport
vendor/yireo/magento2-next-gen-images/Plugin/CorrectImagesInAjaxResponse.php:        BrowserSupport $browserSupport,
vendor/yireo/magento2-next-gen-images/CHANGELOG.md:- Add missing Browser class
vendor/yireo/magento2-next-gen-images/Browser/BrowserSupport.php:namespace Yireo\NextGenImages\Browser;
vendor/yireo/magento2-next-gen-images/Browser/BrowserSupport.php:class BrowserSupport implements ArgumentInterface
vendor/yireo/magento2-next-gen-images/Browser/BrowserSupport.php:     * BrowserSupport constructor.
vendor/yireo/magento2-next-gen-images/Browser/BrowserSupport.php:        if ($this->isChromeBrowser()) {
vendor/yireo/magento2-next-gen-images/Browser/BrowserSupport.php:    public function isChromeBrowser(): bool

**Comment by CalzaFino** [comment]
/public_html$ grep -r Browser vendor/yireo/magento2-webp2
vendor/yireo/magento2-webp2/CHANGELOG.md:- Remove JavaScript check and Browser class

**Comment by CalzaFino** [comment]
Compilation was started.
Area configuration aggregation... 5/9 [===============>------------]  55% 41 secs 410.0 MiB
In ClassReader.php line 45:

  Impossible to process constructor argument Parameter #1 [ <required> Yireo\Webp2\Image\UrlReplacer $urlReplacer ] of Yireo\NextGenImages\Plugin\CorrectIma
  gesInAjaxResponse class


In ClassReader.php line 34:

  Class Yireo\Webp2\Image\UrlReplacer does not exist


setup:di:compile

**Comment by jissereitsma** [comment]
Currently, all tests are succeeding: https://github.com/yireo/Yireo_Webp2/actions Could you double-check that WebP2 is at version 0.9.5 and NextGenImages is at version 0.0.5

**Comment by CalzaFino** [comment]
Thank you! I can confirm it is working with WebP2 Ver 0.9.5 and NextGenImages Ver 0.0.5

**Comment by jissereitsma** [comment]
Thanks, good to hear
