### ISSUE TITLE
Js Error on product page using Safari 14 and version module 0.10.0

### ISSUE THREAD

**Issue by EtienneDutour** [yireo/Yireo_Webp2#64]
Environment : 

Magento 2.3.6
Version module Yireo_WebP2 : 0.10.0
php 7.2.*

Hye,

After upgrading your module to its version 0.10.0 I have this error on my products pages using safari (14.0.*) : 
<img width="1481" alt="Capture d’écran 2021-02-10 à 17 26 29" src="https://user-images.githubusercontent.com/16030071/107622203-cb146c80-6c57-11eb-8cdf-76ac770a0caa.png">

I have downgrade to previous version 0.9.6 where those files aren't there and the module works like a charm on the same Safari version.

Have a great day,
thanks,
Etienne

**Comment by jissereitsma** [comment]
Thanks for posting.

Note that Safari 14 has issues with WebP: https://caniuse.com/?search=webp So seeing things in action would require another browser with full WebP support.

You also didn't mention that something itself was missing or not working, so I'm assuming it's just that you don't like JavaScript errors.

I have now released version 0.10.1 that deals with JavaScript detection of WebP in a different way, bypassing the error.

**Comment by EtienneDutour** [comment]
Sorry ! Indeed I forgot to explain what this error leads to... 

The error leads to the swatch images not rendering in the product page native gallery fotorama.
I'm going to check your new release ;).

Once again I apologize about not mentioning what's going on my product page ! 
Have a great day,

Etienne

**Comment by sebfie** [comment]
Thank you @jissereitsma we needed this upgrade. An issue can be on safari but we can put a website on production without images :)

**Comment by jissereitsma** [comment]
Cool to hear. Let me know if there is any other issue.
