### ISSUE TITLE
Latest version (0.10.5) depencencies

### ISSUE THREAD

**Issue by ivanweiler** [yireo/Yireo_Webp2#69]
Hi Jisse, hope you're doing fine,

Is it dependency issue with todays version:

` yireo/magento2-webp2 0.10.5 requires yireo/magento2-next-gen-images ~0.2.0 -> no matching package found.`

or 0.2.0 is waiting for release? (next-gen-images was updated to 0.1.2)

Thanks for help and fantastic extension ;)

**Comment by jissereitsma** [comment]
Great to hear, thanks
