### ISSUE TITLE
Webp image is occasionally different than Jpeg source

### ISSUE THREAD

**Issue by KimballShop** [yireo/Yireo_Webp2#76]
Webp is 0.10.5, Magento is 2.3.4, PHP is 7.1.33, nextGen is 0.2.1
We have noticed that the Webp thumbnails that come up **on a search** for a few products are incorrect, while the jpg originals are correct - this is checked with Internet Explorer vs Chrome or Edge.  This seems to have happened  with certain sets of products when they were set up in Magento, so it may have been specific to a few days. We were using 0.7.7 at the time. We have cleared the cache several times. The products with the wrong thumbnail are using thumbnails from a product with a similar name. I originally installed with Composer, but an outside web developer made some changes without using Composer (which I found out when I tried an uninstall). I haven't tested this in development mode or by flushing full page cache. **I'd like some guidance on how I can debug this further, or fix it.** As this is an intermittent issue, it's hard to say if the upgrade to 0.10.5 fixed anything.
Here's some image URLs, the ones from IE (Internet Explorer) are correct:
Chrome https://kimballshop.com/pub/media/catalog/product/cache/78bfa443a549d807f8e5d2907d4d9c3d/rdi/rdi/hand-towel-lotus-m008-h_1.webp
IE https://kimballshop.com/pub/media/catalog/product/cache/78bfa443a549d807f8e5d2907d4d9c3d/rdi/rdi/hand-towel-lotus-m008-h_1.jpg

Chrome https://kimballshop.com/pub/media/catalog/product/cache/78bfa443a549d807f8e5d2907d4d9c3d/rdi/rdi/bath-towel-lotus-m008-b_1.webp
IE https://kimballshop.com/pub/media/catalog/product/cache/78bfa443a549d807f8e5d2907d4d9c3d/rdi/rdi/bath-towel-lotus-m008-b_1.jpg

Chrome https://kimballshop.com/pub/media/catalog/product/cache/78bfa443a549d807f8e5d2907d4d9c3d/rdi/rdi/hand-stitched-gray-coverlet-cv-gray_1.webp
IE https://kimballshop.com/pub/media/catalog/product/cache/78bfa443a549d807f8e5d2907d4d9c3d/rdi/rdi/hand-stitched-gray-coverlet-cv-gray_1.jpg

Chrome https://kimballshop.com/pub/media/catalog/product/cache/78bfa443a549d807f8e5d2907d4d9c3d/rdi/rdi/sham-white-sh-white_1.webp
IE https://kimballshop.com/pub/media/catalog/product/cache/78bfa443a549d807f8e5d2907d4d9c3d/rdi/rdi/sham-white-sh-white_1.jpg

**Comment by jissereitsma** [comment]
Thanks for addressing this. I assume that you are upgrading PHP today or tomorrow, because if you worry about conversion, upgrading PHP to PHP 7.3 (or preferably Magento 2.4 and PHP 7.4) gives the real boost, not a silly extension like this.

The WebP extension scans for the timestamp of the original image, to determine whether or not the original image is newer than the WebP version. Could you verify those timestamps? Also, could you try to remove one JPG, reload the page and see if it fixed things? What is the filesystem type of the folder where the images are stored?

**Comment by dontbug** [comment]
Hello!

A similar situation. It appeared when the managers removed the picture for the product and then added another picture again.

Use version: 0.10.7

**Comment by jissereitsma** [comment]
Could you upgrade to the latest version to make sure things are not related to older versions?

If the images are different, could you check the timestamps of the images via the filesystem? Is indeed the JPG newer than the WebP? And what kind of filesystem is this? Could you also confirm that there is no CDN in between?

**Comment by jissereitsma** [comment]
Thanks. So the timestamps are different and the extension should be picking up on this. 

Is the Full Page Cache enabled? Because if that's the fact, than the WebP extension is never called upon again, so it is impossible to check whether the WebP image needs updating ...

**Comment by dontbug** [comment]
No. is disabled
![image](https://user-images.githubusercontent.com/8143119/124257122-b700d700-db34-11eb-96c1-5335361f9529.png)

**Comment by dontbug** [comment]
Test this scenario:
1. For product X with existing 3 pictures, try deleting 2 pictures and click save
2. Add 2 new pictures for this picture and click save.
And check if the JPEG / WEBP pictures are different.

**Comment by jissereitsma** [comment]
Could you check whether the NextGenImages setting "Convert images on save" is at its default "No" or changed into "Yes"?

**Comment by dontbug** [comment]
> Could you check whether the NextGenImages setting "Convert images on save" is at its default "No" or changed into "Yes"?

![Screenshot 2021-07-12 105740](https://user-images.githubusercontent.com/8143119/125251457-00ed7800-e300-11eb-9789-7b92d5307fb1.png)

**Comment by nkajic** [comment]
Hi all. This happened to me in limited cases.

Steps to reproduce: 
* Create product A with image image.png
* Create product B with image image.jpg
(notice that product image is same in both, only extension is different)

First product loaded on catalog page will generate .webp variant and other product will use it. Maybe a new filename for next gen images should be image.jpg.webp ? Anyone have better idea? This happens more often in merchants who manually upload product images and name them poorly.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity. Feel free to reopen if needed.
