### ISSUE TITLE
Image Conversion

### ISSUE THREAD

**Issue by drinkingsouls** [yireo/Yireo_Webp2#83]
Hi Jisse,
I've had this module working since Friday morning and it is doing the job. It is very intuitive finding images and converting accordingly.
The issue I am having is that we have a very large image database so there is a lot to process.

Looking through the readme and docs I can't see anything specific about when the images are converted but it seems to be on demand?
For example, the first time a product is visited since activating the module, then the image is converted? It is not automatically created beforehand? It is not converted until it is requested? Is this correct?

The issue I am having with this is that it overwhelms the server quite often. If I open a category page with 50 products in it then the CPU spikes to 100% and I get a Varnish Cache error or a Cloudflare timeout. I can usually refresh and then it will load 30 seconds or so on with all the webps generated. Presumably, once it has been requested and loaded once, the webps then are created so anyone visting thereafter it will be quick to load? 

Is there no way to generate all images prior to request to prevent this lag in loading time? Would one of the settings such as "Convert images" in the configs help with this?

Thank you.

**Comment by jissereitsma** [comment]
Unfortunately, I'm unable to jump in and provide a nobrains-fix. What do you need to make this work? For instance, if you are saying that you want to generate all WebP files beforehands, have you looked into the CLI version of this extension? Also, have you made sure to do tests with the `cwebp` binary to see if it works ok? Etcetera, etcetera.

> For example, the first time a product is visited since activating the module, then the image is converted? It is not automatically created beforehand? It is not converted until it is requested? Is this correct?
Yes, this is correct. It is the description on the extension page :)

> Would one of the settings such as "Convert images" in the configs help with this?
I don't know how you *want* it to help you. But if *your* strategy is to generate the images beforehand, than you don't need the automatic generation anymore. Is that true? If so, the setting could be disabled. But you are in charge of that strategy, not the extension. The extension is just a simple tool for you to come up with the strategy.

**Comment by drinkingsouls** [comment]
Ideally yes, images would be converted to webps before they are requested by the browser which would prevent the category or product crashing/timing out for the user. Something like a CLI command to do so would be ideal. I have looked through your repos and I don't see a CLI plugin for this?

**Comment by jissereitsma** [comment]
The command is actually part of the parent module, that WebP is relying upon: `bin/magento next-gen-images:convert [IMAGE]`. However, when converting 100s of images, using Magento for this would still add huge overhead. Using the `cwebp` binary directly (or using some other non-Magento non-PHP tool) might be better.

**Comment by basvanpoppel** [comment]
I don't have the perfect solution, but I would like to share an idea which might be useful.

By default the webp module creates two webp images: one lossy, one lossless.  It then checks which has the biggest file size, and removes that one. (We're still running tests, but i have yet to find a lossless image of 60% quality with a smaller file size than a lossy one of 100% quality. A 5 megabyte image takes less then half a second for the lossy compression, but the lossless compression takes 20-30 seconds.)

By adding `'encoding'` to the function parameter we can influence this: let it create 'lossy', 'lossless' or 'auto' (that's current, default).

Perhaps this could be added in the module as a config option, but that's up to you @jissereitsma . :)

**Comment by drinkingsouls** [comment]
I found this module ultimately too process heavy to run and thus removed it.
If webp files could have been generated upfront or via cli that would have been a preferable option.
We have a **huge** image database and to generate webps on the fly was massively increasing loading times to users, pages were taking about a minute to load in some instances as it was required to generate on the fly.

**Comment by jissereitsma** [comment]
@basvanpoppel Thanks for the input. Happy to include this in the next release. I hope to dedicate some time to this soon.

@drinkingsouls Yes, they can be generated up front. The setting **Convert images** could be disabled and you then need to do benchmarking to see which mechanism works best. There's a CLI included in the module. But there are other tools written in Go or Node out there that might work better. It's out of scope of this extension, as this extension is only covering a Magento implementation.

**Comment by jissereitsma** [comment]
@basvanpoppel Version 0.11.0 now ships with this option. The default is actually `lossy` (the most performant one), let's see how this goes.
