### ISSUE TITLE
Module comptabible on Magento 2.3.5-p2

### ISSUE THREAD

**Issue by dellg5** [yireo/Yireo_Webp2#84]
Hello, 

We have 3 Magento in version 2.3.5 with fully customized themes. 
Is your module compatible if we have custom themes ? 
How does it work with safari or other browser ?
is it compatible ? About the performance gain, do we really have a performance gain ? 

Thank you for your feedback

**Comment by jissereitsma** [comment]
Thanks for posting an issue. But it sounds less a technical question and more an open sales question. Please note that this is open source, created with hours of work, offered for free and based on voluntary work. As a maintainer of this project, I'm asking little. But the thing that I do ask is that you are proactive in this open source initiative. It might sound picky, but you are putting the responsibility of all these questions with me, while my opinion is that you (not me) should be able to answer these questions.

Here we go:

> We have 3 Magento in version 2.3.5 with fully customized themes. Is your module compatible if we have custom themes ?

Any module is compatible with Magento module if you are able to install it. This is offered for free and the instructions are simple. It usually takes less than 5 minutes to setup, provided the hosting environment is fit for modifying Magento. Why not install this yourself and see if it works? I don't know anything about your custom themes. If you are asking me to take responsibility of your themes that you are maintaining, than it makes me wonder who is capable of extending the theme. 

> How does it work with safari or other browser ?

Check the docs. I'm **not** going to sell WebP to you. If you don't see the benefit of WebP images for your sites, don't bother installing this extension. If you **do** care about performance, you (the owner of the shops, not a third party extension developer that volunteers to create free code) needs to do the math. Which browsers are supported is **not** something to ask the creator of a free extension. You should be able to google this.

> is it compatible ?

See and you will find out.

> About the performance gain, do we really have a performance gain ?

The entire point of WebP is to make images smaller. Why do you question this? Are you believing that larger images are beneficial for performance. I don't understand why you are raising this question here. If you are doubting that smaller images benefit performance, why are you investigating this topic in the first place.

**Comment by jissereitsma** [comment]
Any update on this?

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity. Feel free to reopen if needed.
