### ISSUE TITLE
Base-url mismatch on domain with country suffixes

### ISSUE THREAD

**Issue by lphilippo** [yireo/Yireo_Webp2#85]
Hello all,

Although we have used this module for various sites without any issue, we only just stumbled upon a challenge that we wanted to share here. We found that the current rules that determine whether or not an image URL qualifies for conversion or not, go wrong in a specific use case, involving multiple languages.

If we have various shops with a shared media folder, such as:

```
https/www.domain.com/en
https/www.domain.com/de
```

And the media base URL being:

```
https/www.domain.com/media
```

None of the media catalog images are being replaced, as they will all disqualify in:

```
\Yireo\NextGenImages\Image\HtmlReplacer::isAllowedByImageUrl
```

The base URLs are in this situation never part of the image URL, as the conflict is caused by the country suffix.

There are various straightforward possibilities :

1. Using `$this->url->getBaseUrl(['_type' => UrlInterface::URL_TYPE_MEDIA]);` here. However, this would have the downside that any images coming from your theme would no longer be replaced.

2. Introduce a helper function to retrieve only the domain of the `baseUrl`. This would sort out our situation, but could still cause similar issues if you use a separate subdomain for your media.

3. Extend the check to determine if either the baseUrl or the media baseUrl matches with the provided $imageUrl. This is the one we went for on our environment.

We are more than happy to provide a PR for this, once we know if you agree with the adjustment.

Kind regards

**Comment by lphilippo** [comment]
Sorry, I just realised that this issue should have been reported in the correct repository https://github.com/yireo/Yireo_NextGenImages

I'll close this one and add it there. My apologies.

**Comment by jissereitsma** [comment]
@lphilippo O you didn't need to do that :) Anyway, I hope to pick up on the new issue soon
