### ISSUE TITLE
No Conversion of Category Images

### ISSUE THREAD

**Issue by Heirik** [yireo/Yireo_Webp2#86]
Using Magento 2.4.2p1 the extension works properly on product pages. However, on categories, homepage, shopping cart, etc it does not appear to work. Is the extension limited to catalog product pages only?

The extension shows no errors.

I have tested with both the luma and blank theme as well as a custom theme.

php 7.4
enabled and install via composer
quality 80
convertors cwebp,gd,imagick,wpc,ewww
webp version 0.10.9
nextGenImages 0.1.2

**Comment by jissereitsma** [comment]
Could you double-check the extensions and their releases? The current release of NextGenImages is 0.2.2. And it would be a pity to troubleshoot something that has been fixed already.

To answer your question: The extension works on all pages on the frontend. Category images and WYIWYG images are picked as usual.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity. Feel free to reopen if needed.
