### ISSUE TITLE
Unsupported mime type: image/gif

### ISSUE THREAD

**Issue by McAlex220** [yireo/Yireo_Webp2#87]
Hi.
I have error 

> Unsupported mime type: image/gif

 in **/vendor/rosell-dk/webp-convert/src/Helpers/InputValidator.php**
There is code:
```
    private static $allowedMimeTypes = [
        'image/jpeg',
        'image/png'
    ];
```
This error breaks the page load - 500 error.
If i add 'image/gif' to $allowedMimeTypes - its working fine.
Should it be like that?

**Comment by jissereitsma** [comment]
Thanks for posting. Actually, I'm unable to duplicate this issue. The design is to not pickup on any GIF images because WebP conversion often does not work for GIFs. Which version of both the WebP module and the NextGenImages module are you using?

**Comment by McAlex220** [comment]
"yireo/magento2-webp2": "^0.10.7"
"yireo/magento2-next-gen-images": "0.2.3"
There IS .gif images on this pages. But it should just skip them, right?

**Comment by jissereitsma** [comment]
Yes, indeed,, they should be skipped. I've tested this with multiple GIFs and in my case, things just worked without issues. Even more, the code itself literally scans for PNG and JPG, and not GIF:  https://github.com/yireo/Yireo_NextGenImages/blob/master/Image/HtmlReplacer.php#L62

Could you copy the specific GIF HTML tag that causes this issue?

**Comment by McAlex220** [comment]
It was simple img tag:<img src="https://site.com/pub/media/catalog/product/cache/d979025a57988e55e13e88db1acfcd00/1/8/187144c86c018a9a2b0a.gif" title="title">

**Comment by McAlex220** [comment]
It was simple img tag
<img src="https://xite.com/pub/media/catalog/product/cache/d979025a57988e55e13e88db1acfcd00/1/8/187144c86c018a9a2b0a.gif" title="title ?">

The problem is - i can't reproduce it now either..
I've revert 
```
  private static $allowedMimeTypes = [
        'image/jpeg',
        'image/png'
    ];
```
in /vendor/rosell-dk/webp-convert/src/Helpers/InputValidator.php and seems all working fine with gif images on the page.. 

But there was one product in popular products list on the product pages with .gif image that caused error(as i think). Now that product is not in popular products list and i can't test it more thoroughly. 

Again, other product page with other product(with .gif img) in popular products list - now works fine(before not tested, i think).

I don't really know why the problem was. Never mind. If it will comeback - i'll give you response here.
Thank you for your time!

**Comment by Morgy93** [comment]
Same error here in a category page:

```
Unsupported mime type: image/gif

#1 WebPConvert\Helpers\InputValidator::checkSource() called at [vendor/rosell-dk/webp-convert/src/Helpers/InputValidator.php:58]
#2 WebPConvert\Helpers\InputValidator::checkSourceAndDestination() called at [vendor/rosell-dk/webp-convert/src/Convert/Converters/AbstractConverter.php:114]
#3 WebPConvert\Convert\Converters\AbstractConverter->__construct() called at [vendor/rosell-dk/webp-convert/src/Convert/Converters/AbstractConverter.php:205]
#4 WebPConvert\Convert\Converters\AbstractConverter::createInstance() called at [vendor/rosell-dk/webp-convert/src/Convert/Converters/AbstractConverter.php:355]
#5 WebPConvert\Convert\Converters\AbstractConverter::convert() called at [vendor/rosell-dk/webp-convert/src/WebPConvert.php:43]
#6 WebPConvert\WebPConvert::convert() called at [vendor/yireo/magento2-webp2/Image/ConvertWrapper.php:37]
#7 Yireo\Webp2\Image\ConvertWrapper->convert() called at [vendor/yireo/magento2-webp2/Convertor/Convertor.php:142]
#8 Yireo\Webp2\Convertor\Convertor->convert() called at [vendor/yireo/magento2-webp2/Convertor/Convertor.php:105]
#9 Yireo\Webp2\Convertor\Convertor->getSourceImage() called at [vendor/yireo/magento2-next-gen-images/Image/HtmlReplacer.php:193]
#10 Yireo\NextGenImages\Image\HtmlReplacer->getAlternativeImagesByImageUrl() called at [vendor/yireo/magento2-next-gen-images/Image/HtmlReplacer.php:80]
#11 Yireo\NextGenImages\Image\HtmlReplacer->replaceImagesInHtml() called at [vendor/yireo/magento2-next-gen-images/Plugin/ReplaceTagsPlugin.php:51]
#12 Yireo\NextGenImages\Plugin\ReplaceTagsPlugin->afterGetOutput() called at [vendor/magento/framework/Interception/Interceptor.php:146]
#13 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#14 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:41]
#15 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#16 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#17 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magezon/module-core/Plugin/View/Result/Layout.php:24]
#20 Magezon\Core\Plugin\View\Result\Layout->aroundRenderResult() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#22 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:23]
#23 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#24 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#25 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
```

I'll try to get more info on what's causing this and why.

**Comment by Morgy93** [comment]
Fun stuff, it is caused by a category image that is `.jpg` but `mime_content_type()` returns `image/gif`.

Maybe backend upload didn't allow `.gif` and the customer just renamed it to `.jpg` to make it work.

Sadly this throws a 500 server error for the category page on production environment so I'd love to get this exception caught.

Like already mentioned the
https://github.com/yireo/Yireo_NextGenImages/blob/master/Image/HtmlReplacer.php#L62
only looks for file extension, but does not consider mime type which then fails hard at
https://github.com/rosell-dk/webp-convert/blob/master/src/Helpers/InputValidator.php#L41

**Comment by jissereitsma** [comment]
@Morgy93 Thanks. This indeed explains your issue. I've added a new quickfix for this in 0.10.11 by simply checking for the specific exception type. 

@McAlex220 I don't know about the issue you had. Possibly somebody did the same: Upload a JPG while it was actually a GIF?

Either way, let me know if this works, so this ticket can be closed.

**Comment by McAlex220** [comment]
Yep, it's possible. Maybe you can add MimeType check for more safety?

**Comment by McAlex220** [comment]
Yes, it's possible. I've tested with new .gif renamed to .jpg - it was 500 error. After upgrade to 0.10.11 - all works fine.

**Comment by andremc420** [comment]
> Thanks for posting. Actually, I'm unable to duplicate this issue. The design is to not pickup on any GIF images because WebP conversion often does not work for GIFs. Which version of both the WebP module and the NextGenImages module are you using?

@jissereitsma I enabled logs and now it's full of warnings about GIFs not existing after conversion. I do have a few animated gifs besides the Magento loader, and they're displaying with no problem except those log entries. Is that how it's supposed to work? Shouldn't those warnings be disabled if the files are being skipped and not converted?

**Comment by jissereitsma** [comment]
The logger in the NextGenImages module is setup to analyse problems, not to minimize logging. In general, the more the logs the better. But if there are no issues any more troubleshoot on the storefront regarding images, I would simply disable logging for performance.
