### ISSUE TITLE
Getting Uncaught Error: Class 'WebPConvert' not found in Frontend.

### ISSUE THREAD

**Issue by mohdbashir** [yireo/Yireo_Webp2#9]
I have installed this extension on my local system with Magento 2.3.0.

It is showing in backend.
https://prnt.sc/p4kq7v

In frontend i am getting the below error:
     Uncaught Error: Class 'WebPConvert' not found in /var/www/html/myproject/app/code/Yireo/Webp2/Image/Convertor.php:59 Stack trace: #0 /var/www/html/myproject/app/code/Yireo/Webp2/Plugin/ReplaceTags.php(94): Yireo\Webp2\Image\Convertor->convert('http://myproj...', 'http://myproj...') #1 /var/www/html/myproject/vendor/magento/framework/Interception/Interceptor.php(146): Yireo\Webp2\Plugin\ReplaceTags->afterGetOutput(Object(Magento\Framework\View\Layout\Interceptor), '\n<script>\n r...') #2 /var/www/html/myproject/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() #3 /var/www/html/myproject/generated/code/Magento/Framework/View/Layout/Interceptor.php(52): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array) #4 /var/www/html/myproject/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput() #5 /var/www/html/myproject/vendor/ma in /var/www/html/myproject/app/code/Yireo/Webp2/Image/Convertor.php on line 59

Please advise.

**Comment by jissereitsma** [comment]
Our instructions do not include copying files randomly to `app/code` unless you are seriously knowing what you are doing. In this case, you didn't read our installation instructions: https://github.com/yireo/Yireo_Webp2/blob/master/INSTALL.md
