### ISSUE TITLE
No conversion on product listing and conversion is showing for only 1 image on home page

### ISSUE THREAD

**Issue by iamsandyrocks** [yireo/Yireo_Webp2#92]
Have just installed the module on live but conversion works on pdp and 1 image on home page is getting converted to webp rest of are not.

The extension shows no errors.

Magento Version is Magento ver. 2.3.5-p1
enabled and install via composer
Composer install output
  - Installing rosell-dk/image-mime-type-guesser (0.3.1): Downloading (100%)         
  - Installing rosell-dk/webp-convert (2.6.0): Downloading (100%)         
  - Installing yireo/magento2-next-gen-images (0.2.3): Downloading (100%)         
  - Installing yireo/magento2-webp2 (0.11.2): Downloading (100%)         

Output of bin/magento dev:di:info "\Magento\Framework\View\LayoutInterface"

DI configuration for the class \Magento\Framework\View\LayoutInterface in the GLOBAL area

Preference: Magento\Framework\View\Layout\Interceptor

Constructor Parameters:
+-------------------------+--------------------------------------------------------+------------------+
| Name                    | Requested Type                                         | Configured Value |
+-------------------------+--------------------------------------------------------+------------------+
| processorFactory        | Magento\Framework\View\Layout\ProcessorFactory         |                  |
| eventManager            | Magento\Framework\Event\ManagerInterface               |                  |
| structure               | Magento\Framework\View\Layout\Data\Structure           |                  |
| messageManager          | Magento\Framework\Message\ManagerInterface             |                  |
| themeResolver           | Magento\Framework\View\Design\Theme\ResolverInterface  |                  |
| readerPool              | Magento\Framework\View\Layout\ReaderPool               |                  |
| generatorPool           | Magento\Framework\View\Layout\GeneratorPool            |                  |
| cache                   | Magento\Framework\Cache\FrontendInterface              |                  |
| readerContextFactory    | Magento\Framework\View\Layout\Reader\ContextFactory    |                  |
| generatorContextFactory | Magento\Framework\View\Layout\Generator\ContextFactory |                  |
| appState                | Magento\Framework\App\State                            |                  |
| logger                  | Psr\Log\LoggerInterface                                |                  |
| cacheable               |                                                        | 1                |
| serializer              | Magento\Framework\Serialize\SerializerInterface        |                  |
+-------------------------+--------------------------------------------------------+------------------+

**Comment by jissereitsma** [comment]
Hi, does the CLI command work `bin/magento next-gen-images:convert /path/to/image.png`?

**Comment by iamsandyrocks** [comment]
yes cli conversion works but image source is not converted in front end. Also webp conversion works on product detail page. But does not work on product listing page

**Comment by jissereitsma** [comment]
I'm unable to reproduce this, so I'm unsure what goes wrong. Could you try disabling the following line to see if it works then? https://github.com/yireo/Yireo_Webp2/blob/master/Convertor/Convertor.php#L135

**Comment by jissereitsma** [comment]
Could you maybe also elaborate on the filesystem where these images are being stored? Is it the exact same (Linux) filesystem that also contains Magento? Or is it a remote share of some kind (like NFS)? Is it a VPS or some kind of cloud like AWS?

**Comment by iamsandyrocks** [comment]
tried disabling the line https://github.com/yireo/Yireo_Webp2/blob/master/Convertor/Convertor.php#L135..but still does not work. We have similar setup on uat server and webp image conversion works perfetctly well. only on production it is not working.

Is there something to do with cloudflare settings ?

**Comment by jissereitsma** [comment]
If the URL to your images is no longer a Magento URL, but a CDN URL instead, then indeed the WebP extension will unable to detect this as a local image. Is the URL changed into a CDN URL?

**Comment by iamsandyrocks** [comment]
yes CDN is enabled on production. any Solution on that then ?

**Comment by iamsandyrocks** [comment]
yes CDN is configured from Magento backend. Also tried with latest version on different instance with CDN enabled still the issue persists

**Comment by jissereitsma** [comment]
Could you confirm this in a precise way? You say that the CDN is configured from the Magento backend but you are not indicating whether the ONLY way to configure the CDN is to set the Media URL to some URL (which would be the Magento way). 

As of yet, I'm unable to reproduce this, and I'm unable to find out what the cause of the problem would be. Have you started debugging things already with XDebug to see which parts of the extension are being called and which are not?

**Comment by iamsandyrocks** [comment]
Yes the only way in magento to set CDN URL is from backend. 
Also if you are saying that you are unable to reproduce  can you confirm if this plugin works for you with CDN URL enabled. Can you share a demo URL for the same ?

**Comment by jissereitsma** [comment]
No, I don't have a demo for this free extension. But we are not troubleshooting my development environment or a demo, we're troubleshooting your environment. And I still don't have a clue what the CDN is that you configured and that is causing issues. Could you share at least a little bit there?

My test-case: I have a working environment without any CDN. Next, under the settings **General > Web > Base URLs > Base URL for User Media Files** I'm setting a new domain (which does not resemble the Base URL, but it is a domain name that is picked up Apache to lead back to the same Magento domain). In other words, http://example.org/media equals http://cdn.example.org. And it works.

I assume you did already, but could you make sure to go through the (updated) support document https://github.com/yireo/Yireo_Webp2/blob/master/SUPPORT.md - especially towards the end.

**Comment by iamsandyrocks** [comment]
Have verified on multiple instances. This plugin does not work with CDN is configured. Removing CDN url this plugin works as expected

**Comment by jissereitsma** [comment]
Thanks for the feedback. Unfortunately, I tried this now on some development environments in production mode and found it to be working. Could you please point to a non-working environment? Because as of yet, I'm unable to reproduce anything.
