### ISSUE TITLE
i am facing issue when i i open the product

### ISSUE THREAD

**Issue by moazzama** [yireo/Yireo_Webp2#94]
1 exception(s):
Exception #0 (Magento\Framework\View\Asset\File\NotFoundException): URL "pub/media/wysiwyg/pdf2.png" is not matched with a local file

https://dev1.ebygghandel.se/komposittrall-teak-marine-40-massiv-trallbrada-19-146-4800-mm.html

**Comment by jissereitsma** [comment]
So I assume that the file "pub/media/wysiwyg/pdf2.png" is not existing?

**Comment by moazzama** [comment]
Hi 
that image is already in folder
please find the attachment 
![check](https://user-images.githubusercontent.com/68050583/129720802-b05685a2-e04a-4ce8-9edb-ee086778c42f.PNG)
Thanks

**Comment by jissereitsma** [comment]
Strange. I'm not sure why an existing file would be classified as not found, but you can use the `SUPPORT.md` instructions to troubleshoot this. I've released a new version of the NextGenImages module (version 0.2.8) to make sure the exception doesn't reach the frontend though. So upgrading the package should fix the exception. If, after this, you are still wondering why the image is not found, please see the support instructions first.

**Comment by moazzama** [comment]
ok Thanks
