### ISSUE TITLE
UrtlConvertor error in parsing

### ISSUE THREAD

**Issue by przmak** [yireo/Yireo_Webp2#96]
File: html/vendor/yireo/magento2-next-gen-images/Image/UrlConvertor.php
Function: getFilenameFromUrl
Magento version: 2.3.3-p1

**$url to parse:**
https://localhost/static/version1630940597/frontend/Theme/base/en_GB/Magento_Catalog/images/product/placeholder/small_image.jpg

**Outcome:**
/var/www/html/static/version1630940597/frontend/Theme/base/en_GB/Magento_Catalog/images/product/placeholder/small_image.jpg

**Expected Outcome:**
/var/www/html/**pub**/static/version1630940597/frontend/Theme/base/en_GB/Magento_Catalog/images/product/placeholder/small_image.jpg

**Comment by przmak** [comment]
Here is a quick solution how the function should look more or less:

`/**
     * @param string $url
     * @return string
     * @throws FileSystemException
     * @throws NoSuchEntityException
     */
    public function getFilenameFromUrl(string $url): string
    {
        if ($this->isLocal($url) === false) {
            throw new NotFoundException((string)__('URL "' . $url . '" does not appear to be a local file'));
        }

        if (strpos($url, $this->getMediaUrl()) !== false) {
            return str_replace($this->getMediaUrl(), $this->getMediaFolder() . '/', $url);
        }

        $pattern = '/\/static\/version([0-9]+\/)/';
        if (preg_match($pattern, $url)) {
            $url = preg_replace($pattern, '/', $url);
            return str_replace($this->getBaseUrl(), $this->directoryList->getPath('static') . '/', $url);
        }

        if (strpos($url, $this->getBaseUrl()) !== false) {
            return str_replace($this->getBaseUrl(), $this->getBaseFolder() . '/', $url);
        }

        if (preg_match('/^\//', $url)) {
            return $this->getBaseFolder() . $url;
        }

        throw new NotFoundException((string)__('URL "' . $url . '" is not matched with a local file'));
    }`

**Comment by jissereitsma** [comment]
Could you turn this into a Pull Request of this file instead? https://github.com/yireo/Yireo_NextGenImages/blob/master/Image/UrlConvertor.php It requires just a couple of clicks more, but it allows us to discuss things on a line-level basis, instead of going forth and back copying code.

**Comment by jissereitsma** [comment]
Could you also confirm that the CLI commands indeed show this mismatch and that you are using the latest version of both WebP2 and NextGenImages extension as well?

**Comment by przmak** [comment]
I will transfer this to issue to other repo:
I'm using:
"name": "yireo/magento2-next-gen-images",
"version": "0.2.7",
&
"name": "yireo/magento2-webp2",
"version": "0.10.11",
    
Will check in the meantime if this is solved in the newer version.
Cheers
