### ISSUE TITLE
Menu not showing in backend

### ISSUE THREAD

**Issue by Eddcapone** [yireo/Yireo_Webp2#97]
I installed the extension on 2.4.2 EE by copying the module into app/code/. But there is no Yireo setting showing in the backend at System -> Configuration. The extension is enabled

**Comment by Eddcapone** [comment]
It looks like the extension has dependencies, you have to install it by using composer to make it work.

The instructions are also missing the information, that you have to enable the module "Yireo_NextGenImages"

**Comment by jissereitsma** [comment]
@Eddcapone Thanks, the comments on the NextGenImages have been added to the instructions: https://github.com/yireo/Yireo_Webp2/blob/master/INSTALL.md
