### ISSUE TITLE
Not working with slick slider

### ISSUE THREAD

**Issue by Eddcapone** [yireo/Yireo_Webp2#99]
I have a slick slider on my homepage. If I enable the extension then the images are not getting loaded.

I inspected the source code. It even replaces everything correctly and adds picture tags.
I checked the source links and every source link is working and showing an image if I open it in the browser.

But the image is not shown.

I am using 2.4.2 EE

**Comment by jissereitsma** [comment]
Thanks for posting. The workings of this extension are simple: Convert any `img` tags into `picture` tags and add a WebP image to it. Have you confirmed that the JavaScript effect you mentioned is supporting `picture` tags?

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity. Feel free to reopen if needed.
